"""Inventory data for the Mastemy 1,000+ course catalogue (Batch 0).

Certification codes below come from the author's knowledge unless listed in
data_sources.OFFICIALLY_VERIFIED_CODES. Unless verified, every row is emitted
as `unverified-needs-official-check` with an empty `verified_on`.
"""

CATEGORIES = {
    # code: (name, minimum)
    "AI":  ("Artificial Intelligence", 140),
    "MIC": ("Microsoft", 100),
    "GCP": ("Google", 55),
    "AWS": ("AWS", 55),
    "PRG": ("Programming & Software", 140),
    "DAT": ("Data & Analytics", 75),
    "CYB": ("Cybersecurity & IT", 85),
    "FIN": ("Finance & Accounting", 100),
    "PMB": ("Project Management & Business Analysis", 55),
    "HLT": ("Healthcare", 35),
    "ENG": ("Engineering & Supply Chain", 50),
    "BUS": ("Business & Enterprise Platforms", 55),
    "LNG": ("Languages & English Testing", 30),
    "CRE": ("Creative & Media", 25),
}


def c(fam, slug, title, body, code, level, sub, hrs):
    return dict(family=fam, slug=slug, title=title, awarding_body=body,
                official_exam_code=code, level=level, subcategory=sub, hours=hrs)


F, I, A = "foundation", "intermediate", "advanced"

CERTS = {
"MIC": [
    c("MS", "AZ900", "Microsoft Azure Fundamentals (AZ-900) Exam Prep", "Microsoft", "AZ-900", F, "Azure", 25),
    c("MS", "AI901", "Microsoft Azure AI Fundamentals (AI-901) Exam Prep", "Microsoft", "AI-901", F, "Azure AI", 25),
    c("MS", "SC900", "Microsoft Security, Compliance, and Identity Fundamentals (SC-900) Exam Prep", "Microsoft", "SC-900", F, "Security", 25),
    c("MS", "DP900", "Microsoft Azure Data Fundamentals (DP-900) Exam Prep", "Microsoft", "DP-900", F, "Data", 25),
    c("MS", "PL900", "Microsoft Power Platform Fundamentals (PL-900) Exam Prep", "Microsoft", "PL-900", F, "Power Platform", 25),
    c("MS", "AB900", "Microsoft Copilot & Agent Administration Fundamentals (AB-900) Exam Prep", "Microsoft", "AB-900", F, "Microsoft 365", 18),
    c("MS", "AZ104", "Microsoft Azure Administrator (AZ-104) Exam Prep", "Microsoft", "AZ-104", I, "Azure", 50),
    c("MS", "AZ305", "Designing Microsoft Azure Infrastructure Solutions (AZ-305) Exam Prep", "Microsoft", "AZ-305", A, "Azure", 50),
    c("MS", "AZ400", "Designing and Implementing Microsoft DevOps Solutions (AZ-400) Exam Prep", "Microsoft", "AZ-400", A, "Azure", 50),
    c("MS", "AZ700", "Designing and Implementing Azure Networking Solutions (AZ-700) Exam Prep", "Microsoft", "AZ-700", A, "Azure", 45),
    c("MS", "AZ140", "Configuring and Operating Microsoft Azure Virtual Desktop (AZ-140) Exam Prep", "Microsoft", "AZ-140", I, "Azure", 35),
    c("MS", "AZ120", "Planning and Administering Azure for SAP Workloads (AZ-120) Exam Prep", "Microsoft", "AZ-120", A, "Azure", 35),
    c("MS", "AI103", "Azure AI App & Agent Developer (AI-103) Exam Prep", "Microsoft", "AI-103", I, "Azure AI", 45),
    c("MS", "AI200", "Microsoft AI-200 Developer Exam Prep (successor to AZ-204)", "Microsoft", "AI-200", I, "Azure AI", 45),
    c("MS", "AI300", "Microsoft AI-300 Exam Prep (successor to DP-100)", "Microsoft", "AI-300", I, "Azure AI", 45),
    c("MS", "DP300", "Administering Microsoft Azure SQL Solutions (DP-300) Exam Prep", "Microsoft", "DP-300", I, "Data", 40),
    c("MS", "DP420", "Designing and Implementing Cloud-Native Applications Using Azure Cosmos DB (DP-420) Exam Prep", "Microsoft", "DP-420", A, "Data", 40),
    c("MS", "DP600", "Implementing Analytics Solutions Using Microsoft Fabric (DP-600) Exam Prep", "Microsoft", "DP-600", I, "Fabric", 40),
    c("MS", "DP700", "Implementing Data Engineering Solutions Using Microsoft Fabric (DP-700) Exam Prep", "Microsoft", "DP-700", I, "Fabric", 40),
    c("MS", "PL200", "Microsoft Power Platform Functional Consultant (PL-200) Exam Prep", "Microsoft", "PL-200", I, "Power Platform", 40),
    c("MS", "PL300", "Microsoft Power BI Data Analyst (PL-300) Exam Prep", "Microsoft", "PL-300", I, "Power BI", 40),
    c("MS", "PL400", "Microsoft Power Platform Developer (PL-400) Exam Prep", "Microsoft", "PL-400", A, "Power Platform", 40),
    c("MS", "PL600", "Microsoft Power Platform Solution Architect (PL-600) Exam Prep", "Microsoft", "PL-600", A, "Power Platform", 40),
    c("MS", "SC100", "Microsoft Cybersecurity Architect (SC-100) Exam Prep", "Microsoft", "SC-100", A, "Security", 45),
    c("MS", "SC200", "Microsoft Security Operations Analyst (SC-200) Exam Prep", "Microsoft", "SC-200", I, "Security", 45),
    c("MS", "SC300", "Microsoft Identity and Access Administrator (SC-300) Exam Prep", "Microsoft", "SC-300", I, "Security", 40),
    c("MS", "SC401", "Microsoft Information Security Administrator (SC-401) Exam Prep", "Microsoft", "SC-401", I, "Security", 40),
    c("MS", "MS102", "Microsoft 365 Administrator (MS-102) Exam Prep", "Microsoft", "MS-102", I, "Microsoft 365", 45),
    c("MS", "MD102", "Microsoft Endpoint Administrator (MD-102) Exam Prep", "Microsoft", "MD-102", I, "Microsoft 365", 40),
    c("MS", "MS700", "Managing Microsoft Teams (MS-700) Exam Prep", "Microsoft", "MS-700", I, "Microsoft 365", 30),
    c("MS", "MS721", "Collaboration Communications Systems Engineer (MS-721) Exam Prep", "Microsoft", "MS-721", I, "Microsoft 365", 30),
    c("MS", "MB210", "Dynamics 365 Sales Functional Consultant (MB-210) Exam Prep", "Microsoft", "MB-210", I, "Dynamics 365", 30),
    c("MS", "MB220", "Dynamics 365 Customer Insights - Journeys Functional Consultant (MB-220) Exam Prep", "Microsoft", "MB-220", I, "Dynamics 365", 30),
    c("MS", "MB230", "Dynamics 365 Customer Service Functional Consultant (MB-230) Exam Prep", "Microsoft", "MB-230", I, "Dynamics 365", 30),
    c("MS", "MB240", "Dynamics 365 Field Service Functional Consultant (MB-240) Exam Prep", "Microsoft", "MB-240", I, "Dynamics 365", 30),
    c("MS", "MB280", "Dynamics 365 Customer Experience Analyst (MB-280) Exam Prep", "Microsoft", "MB-280", I, "Dynamics 365", 30),
    c("MS", "MB310", "Dynamics 365 Finance Functional Consultant (MB-310) Exam Prep", "Microsoft", "MB-310", I, "Dynamics 365", 35),
    c("MS", "MB330", "Dynamics 365 Supply Chain Management Functional Consultant (MB-330) Exam Prep", "Microsoft", "MB-330", I, "Dynamics 365", 35),
    c("MS", "MB335", "Dynamics 365 Supply Chain Management Functional Consultant Expert (MB-335) Exam Prep", "Microsoft", "MB-335", A, "Dynamics 365", 35),
    c("MS", "MB500", "Dynamics 365 Finance and Operations Apps Developer (MB-500) Exam Prep", "Microsoft", "MB-500", A, "Dynamics 365", 40),
    c("MS", "MB700", "Dynamics 365 Finance and Operations Apps Solution Architect (MB-700) Exam Prep", "Microsoft", "MB-700", A, "Dynamics 365", 35),
    c("MS", "MB800", "Dynamics 365 Business Central Functional Consultant (MB-800) Exam Prep", "Microsoft", "MB-800", I, "Dynamics 365", 30),
    c("MS", "MB820", "Dynamics 365 Business Central Developer (MB-820) Exam Prep", "Microsoft", "MB-820", A, "Dynamics 365", 35),
    c("GH", "GH900", "GitHub Foundations (GH-900) Exam Prep", "GitHub (Microsoft)", "GH-900", F, "GitHub", 15),
    c("GH", "GH100", "GitHub Administration (GH-100) Exam Prep", "GitHub (Microsoft)", "GH-100", I, "GitHub", 20),
    c("GH", "GH200", "GitHub Actions (GH-200) Exam Prep", "GitHub (Microsoft)", "GH-200", I, "GitHub", 20),
    c("GH", "GH300", "GitHub Copilot (GH-300) Exam Prep", "GitHub (Microsoft)", "GH-300", I, "GitHub", 18),
    c("GH", "GH500", "GitHub Advanced Security (GH-500) Exam Prep", "GitHub (Microsoft)", "GH-500", I, "GitHub", 20),
    c("MOS", "MO200", "Microsoft Office Specialist: Excel Associate (MO-200) Exam Prep", "Microsoft / Certiport", "MO-200", F, "Microsoft Office Specialist", 20),
    c("MOS", "MO201", "Microsoft Office Specialist: Excel Expert (MO-201) Exam Prep", "Microsoft / Certiport", "MO-201", I, "Microsoft Office Specialist", 25),
    c("MOS", "MO100", "Microsoft Office Specialist: Word Associate (MO-100) Exam Prep", "Microsoft / Certiport", "MO-100", F, "Microsoft Office Specialist", 15),
    c("MOS", "MO300", "Microsoft Office Specialist: PowerPoint Associate (MO-300) Exam Prep", "Microsoft / Certiport", "MO-300", F, "Microsoft Office Specialist", 12),
],
"AWS": [
    c("AWS", "CLFC02", "AWS Certified Cloud Practitioner (CLF-C02) Exam Prep", "Amazon Web Services", "CLF-C02", F, "Foundational", 40),
    c("AWS", "AIFC01", "AWS Certified AI Practitioner (AIF-C01) Exam Prep", "Amazon Web Services", "AIF-C01", F, "Foundational", 25),
    c("AWS", "SAAC03", "AWS Certified Solutions Architect - Associate (SAA-C03) Exam Prep", "Amazon Web Services", "SAA-C03", I, "Associate", 55),
    c("AWS", "DVAC02", "AWS Certified Developer - Associate (DVA-C02) Exam Prep", "Amazon Web Services", "DVA-C02", I, "Associate", 50),
    c("AWS", "SOA", "AWS Certified CloudOps Engineer / SysOps Administrator - Associate Exam Prep", "Amazon Web Services", "", I, "Associate", 50),
    c("AWS", "DEAC01", "AWS Certified Data Engineer - Associate (DEA-C01) Exam Prep", "Amazon Web Services", "DEA-C01", I, "Associate", 50),
    c("AWS", "MLAC01", "AWS Certified Machine Learning Engineer - Associate (MLA-C01) Exam Prep", "Amazon Web Services", "MLA-C01", I, "Associate", 50),
    c("AWS", "SAPC02", "AWS Certified Solutions Architect - Professional (SAP-C02) Exam Prep", "Amazon Web Services", "SAP-C02", A, "Professional", 70),
    c("AWS", "DOPC02", "AWS Certified DevOps Engineer - Professional (DOP-C02) Exam Prep", "Amazon Web Services", "DOP-C02", A, "Professional", 70),
    c("AWS", "ANSC01", "AWS Certified Advanced Networking - Specialty (ANS-C01) Exam Prep", "Amazon Web Services", "ANS-C01", A, "Specialty", 60),
    c("AWS", "SCS", "AWS Certified Security - Specialty Exam Prep", "Amazon Web Services", "", A, "Specialty", 60),
],
"GCP": [
    c("GCP", "CDL", "Google Cloud Digital Leader Exam Prep", "Google Cloud", "CDL", F, "Foundational", 20),
    c("GCP", "GAIL", "Google Cloud Generative AI Leader Exam Prep", "Google Cloud", "", F, "Foundational", 20),
    c("GCP", "ACE", "Google Cloud Associate Cloud Engineer Exam Prep", "Google Cloud", "ACE", I, "Associate", 45),
    c("GCP", "ADP", "Google Cloud Associate Data Practitioner Exam Prep", "Google Cloud", "", I, "Associate", 35),
    c("GCP", "AGWA", "Google Workspace Administrator Exam Prep", "Google Cloud", "", I, "Workspace", 30),
    c("GCP", "PCA", "Google Cloud Professional Cloud Architect Exam Prep", "Google Cloud", "PCA", A, "Professional", 60),
    c("GCP", "PDE", "Google Cloud Professional Data Engineer Exam Prep", "Google Cloud", "PDE", A, "Professional", 60),
    c("GCP", "PCD", "Google Cloud Professional Cloud Developer Exam Prep", "Google Cloud", "PCD", A, "Professional", 55),
    c("GCP", "PCDOE", "Google Cloud Professional Cloud DevOps Engineer Exam Prep", "Google Cloud", "", A, "Professional", 55),
    c("GCP", "PCNE", "Google Cloud Professional Cloud Network Engineer Exam Prep", "Google Cloud", "PCNE", A, "Professional", 55),
    c("GCP", "PCSE", "Google Cloud Professional Cloud Security Engineer Exam Prep", "Google Cloud", "PCSE", A, "Professional", 55),
    c("GCP", "PMLE", "Google Cloud Professional Machine Learning Engineer Exam Prep", "Google Cloud", "PMLE", A, "Professional", 60),
    c("GCP", "PCDBE", "Google Cloud Professional Cloud Database Engineer Exam Prep", "Google Cloud", "", A, "Professional", 50),
    c("GCP", "SECOPS", "Google Cloud Professional Security Operations Engineer Exam Prep", "Google Cloud", "", A, "Professional", 50),
    c("GADS", "GADSSEARCH", "Google Ads Search Certification Prep", "Google", "", F, "Google Marketing", 8),
    c("GADS", "GADSDISPLAY", "Google Ads Display Certification Prep", "Google", "", F, "Google Marketing", 8),
    c("GADS", "GADSVIDEO", "Google Ads Video Certification Prep", "Google", "", F, "Google Marketing", 8),
    c("GADS", "GA4CERT", "Google Analytics Certification Prep", "Google", "", F, "Google Marketing", 10),
],
"AI": [
    c("NVIDIA", "NCAGENL", "NVIDIA-Certified Associate: Generative AI LLMs Exam Prep", "NVIDIA", "NCA-GENL", I, "AI Certifications", 30),
    c("NVIDIA", "NCAAIIO", "NVIDIA-Certified Associate: AI Infrastructure and Operations Exam Prep", "NVIDIA", "NCA-AIIO", I, "AI Certifications", 30),
    c("IAPP", "AIGP", "IAPP Artificial Intelligence Governance Professional (AIGP) Exam Prep", "IAPP", "AIGP", A, "AI Governance", 35),
    c("ISACA", "AAIA", "ISACA Advanced in AI Audit (AAIA) Exam Prep", "ISACA", "AAIA", A, "AI Governance", 35),
    c("ISACA", "AAISM", "ISACA Advanced in AI Security Management (AAISM) Exam Prep", "ISACA", "AAISM", A, "AI Governance", 35),
    c("ISO", "ISO42001F", "ISO/IEC 42001 AI Management System Foundation Prep", "Various accredited bodies", "", F, "AI Governance", 15),
],
"PRG": [
    c("ORA", "1Z0829", "Oracle Certified Professional: Java SE 17 Developer (1Z0-829) Exam Prep", "Oracle", "1Z0-829", I, "Java", 60),
    c("ORA", "1Z0830", "Oracle Certified Professional: Java SE 21 Developer (1Z0-830) Exam Prep", "Oracle", "1Z0-830", I, "Java", 60),
    c("PYI", "PCEP", "Python Institute PCEP Certified Entry-Level Python Programmer Exam Prep", "OpenEDG Python Institute", "PCEP-30-02", F, "Python", 25),
    c("PYI", "PCAP", "Python Institute PCAP Certified Associate in Python Programming Exam Prep", "OpenEDG Python Institute", "PCAP-31-03", I, "Python", 40),
    c("LF", "KCNA", "Kubernetes and Cloud Native Associate (KCNA) Exam Prep", "Linux Foundation / CNCF", "KCNA", F, "Cloud Native", 25),
    c("LF", "KCSA", "Kubernetes and Cloud Native Security Associate (KCSA) Exam Prep", "Linux Foundation / CNCF", "KCSA", F, "Cloud Native", 25),
    c("LF", "CKA", "Certified Kubernetes Administrator (CKA) Knowledge Prep", "Linux Foundation / CNCF", "CKA", I, "Cloud Native", 50),
    c("LF", "CKAD", "Certified Kubernetes Application Developer (CKAD) Knowledge Prep", "Linux Foundation / CNCF", "CKAD", I, "Cloud Native", 45),
    c("LF", "CKS", "Certified Kubernetes Security Specialist (CKS) Knowledge Prep", "Linux Foundation / CNCF", "CKS", A, "Cloud Native", 50),
    c("LF", "LFCS", "Linux Foundation Certified System Administrator (LFCS) Knowledge Prep", "Linux Foundation", "LFCS", I, "Linux", 45),
    c("LF", "PCA", "Prometheus Certified Associate (PCA) Exam Prep", "Linux Foundation / CNCF", "PCA", I, "Cloud Native", 25),
    c("RH", "EX200", "Red Hat Certified System Administrator (RHCSA, EX200) Knowledge Prep", "Red Hat", "EX200", I, "Linux", 50),
    c("RH", "EX294", "Red Hat Certified Engineer (RHCE, EX294) Knowledge Prep", "Red Hat", "EX294", A, "Linux", 50),
    c("RH", "EX188", "Red Hat Certified Specialist in Containers (EX188) Knowledge Prep", "Red Hat", "EX188", I, "Linux", 30),
    c("HC", "TFA", "HashiCorp Certified: Terraform Associate Exam Prep", "HashiCorp", "", I, "DevOps", 30),
    c("HC", "VLTA", "HashiCorp Certified: Vault Associate Exam Prep", "HashiCorp", "", I, "DevOps", 25),
    c("SF", "PD1", "Salesforce Certified Platform Developer I Exam Prep", "Salesforce", "", I, "Salesforce Development", 45),
    c("SF", "JSD1", "Salesforce Certified JavaScript Developer I Exam Prep", "Salesforce", "", I, "Salesforce Development", 35),
    c("ORA", "1Z0071", "Oracle Database SQL Certified Associate (1Z0-071) Exam Prep", "Oracle", "1Z0-071", I, "Databases", 40),
],
"DAT": [
    c("DBX", "DEA", "Databricks Certified Data Engineer Associate Exam Prep", "Databricks", "", I, "Databricks", 35),
    c("DBX", "DEP", "Databricks Certified Data Engineer Professional Exam Prep", "Databricks", "", A, "Databricks", 45),
    c("DBX", "DAA", "Databricks Certified Data Analyst Associate Exam Prep", "Databricks", "", I, "Databricks", 30),
    c("DBX", "MLA", "Databricks Certified Machine Learning Associate Exam Prep", "Databricks", "", I, "Databricks", 35),
    c("DBX", "MLP", "Databricks Certified Machine Learning Professional Exam Prep", "Databricks", "", A, "Databricks", 45),
    c("DBX", "GAIEA", "Databricks Certified Generative AI Engineer Associate Exam Prep", "Databricks", "", I, "Databricks", 35),
    c("DBX", "SPARK", "Databricks Certified Associate Developer for Apache Spark Exam Prep", "Databricks", "", I, "Databricks", 35),
    c("SNOW", "CORE", "SnowPro Core Certification Exam Prep", "Snowflake", "COF-C02", I, "Snowflake", 35),
    c("SNOW", "ADVARCH", "SnowPro Advanced: Architect Exam Prep", "Snowflake", "", A, "Snowflake", 45),
    c("SNOW", "ADVDE", "SnowPro Advanced: Data Engineer Exam Prep", "Snowflake", "", A, "Snowflake", 45),
    c("SNOW", "ADVDA", "SnowPro Advanced: Data Analyst Exam Prep", "Snowflake", "", A, "Snowflake", 40),
    c("SNOW", "ADVADM", "SnowPro Advanced: Administrator Exam Prep", "Snowflake", "", A, "Snowflake", 40),
    c("TAB", "TDA", "Tableau Certified Data Analyst Exam Prep", "Salesforce / Tableau", "", I, "BI Tools", 30),
    c("TAB", "TDSPEC", "Tableau Desktop Foundations / Specialist Exam Prep", "Salesforce / Tableau", "", F, "BI Tools", 20),
    c("CMPT", "DATAPLUS", "CompTIA Data+ Exam Prep", "CompTIA", "", I, "Vendor-neutral", 35),
    c("CMPT", "DATAX", "CompTIA DataX Exam Prep", "CompTIA", "", A, "Vendor-neutral", 45),
],
"CYB": [
    c("CMPT", "APLUS1", "CompTIA A+ Core 1 Exam Prep", "CompTIA", "220-1201", F, "CompTIA", 40),
    c("CMPT", "APLUS2", "CompTIA A+ Core 2 Exam Prep", "CompTIA", "220-1202", F, "CompTIA", 40),
    c("CMPT", "TECHPLUS", "CompTIA Tech+ Exam Prep", "CompTIA", "FC0-U71", F, "CompTIA", 20),
    c("CMPT", "NETPLUS", "CompTIA Network+ (N10-009) Exam Prep", "CompTIA", "N10-009", I, "CompTIA", 45),
    c("CMPT", "SY0701", "CompTIA Security+ (SY0-701) Exam Prep", "CompTIA", "SY0-701", I, "CompTIA", 45),
    c("CMPT", "CYSA", "CompTIA CySA+ Exam Prep", "CompTIA", "CS0-003", I, "CompTIA", 45),
    c("CMPT", "PENTEST", "CompTIA PenTest+ Exam Prep", "CompTIA", "PT0-003", I, "CompTIA", 45),
    c("CMPT", "SECX", "CompTIA SecurityX Exam Prep", "CompTIA", "CAS-005", A, "CompTIA", 55),
    c("CMPT", "LINUX", "CompTIA Linux+ Exam Prep", "CompTIA", "", I, "CompTIA", 45),
    c("CMPT", "CLOUD", "CompTIA Cloud+ Exam Prep", "CompTIA", "CV0-004", I, "CompTIA", 40),
    c("CMPT", "SERVER", "CompTIA Server+ Exam Prep", "CompTIA", "SK0-005", I, "CompTIA", 40),
    c("ISC2", "CC", "ISC2 Certified in Cybersecurity (CC) Exam Prep", "ISC2", "CC", F, "ISC2", 20),
    c("ISC2", "SSCP", "ISC2 SSCP Exam Prep", "ISC2", "SSCP", I, "ISC2", 45),
    c("ISC2", "CISSP", "ISC2 CISSP Exam Prep", "ISC2", "CISSP", A, "ISC2", 80),
    c("ISC2", "CCSP", "ISC2 CCSP Exam Prep", "ISC2", "CCSP", A, "ISC2", 60),
    c("ISC2", "CSSLP", "ISC2 CSSLP Exam Prep", "ISC2", "CSSLP", A, "ISC2", 50),
    c("ISC2", "CGRC", "ISC2 CGRC Exam Prep", "ISC2", "CGRC", A, "ISC2", 45),
    c("ISC2", "ISSAP", "ISC2 CISSP-ISSAP Concentration Exam Prep", "ISC2", "ISSAP", A, "ISC2", 40),
    c("ISC2", "ISSEP", "ISC2 CISSP-ISSEP Concentration Exam Prep", "ISC2", "ISSEP", A, "ISC2", 40),
    c("ISC2", "ISSMP", "ISC2 CISSP-ISSMP Concentration Exam Prep", "ISC2", "ISSMP", A, "ISC2", 40),
    c("ISACA", "CISA", "ISACA CISA Exam Prep", "ISACA", "CISA", A, "ISACA", 70),
    c("ISACA", "CISM", "ISACA CISM Exam Prep", "ISACA", "CISM", A, "ISACA", 65),
    c("ISACA", "CRISC", "ISACA CRISC Exam Prep", "ISACA", "CRISC", A, "ISACA", 60),
    c("ISACA", "CGEIT", "ISACA CGEIT Exam Prep", "ISACA", "CGEIT", A, "ISACA", 60),
    c("ISACA", "CDPSE", "ISACA CDPSE Exam Prep", "ISACA", "CDPSE", A, "ISACA", 55),
    c("ISACA", "ITAF", "ISACA IT Audit Fundamentals Certificate Prep", "ISACA", "", F, "ISACA", 20),
    c("ISACA", "CCOA", "ISACA Certified Cybersecurity Operations Analyst (CCOA) Exam Prep", "ISACA", "CCOA", I, "ISACA", 45),
    c("CSCO", "CCNA", "Cisco CCNA (200-301) Exam Prep", "Cisco", "200-301", I, "Cisco", 70),
    c("CSCO", "CCSTNET", "Cisco Certified Support Technician (CCST) Networking Exam Prep", "Cisco", "", F, "Cisco", 25),
    c("CSCO", "CCSTCYB", "Cisco Certified Support Technician (CCST) Cybersecurity Exam Prep", "Cisco", "", F, "Cisco", 25),
    c("CSCO", "CBROPS", "Cisco CyberOps Associate (CBROPS 200-201) Exam Prep", "Cisco", "200-201", I, "Cisco", 45),
    c("CSCO", "ENCOR", "Cisco CCNP Enterprise Core (ENCOR 350-401) Exam Prep", "Cisco", "350-401", A, "Cisco", 70),
    c("CSCO", "ENARSI", "Cisco CCNP Enterprise Advanced Routing (ENARSI 300-410) Exam Prep", "Cisco", "300-410", A, "Cisco", 55),
    c("CSCO", "SCOR", "Cisco CCNP Security Core (SCOR 350-701) Exam Prep", "Cisco", "350-701", A, "Cisco", 65),
    c("CSCO", "AUTOCORE", "Cisco Automation Core (CCNP Automation) Exam Prep", "Cisco", "", A, "Cisco", 55),
    c("ECC", "CEH", "EC-Council Certified Ethical Hacker (CEH) Knowledge Exam Prep", "EC-Council", "312-50", I, "Offensive Security", 50),
    c("GIAC", "GSEC", "GIAC Security Essentials (GSEC) Exam Prep", "GIAC", "GSEC", I, "GIAC", 50),
    c("SNOW", "CSA", "ServiceNow Certified System Administrator Exam Prep", "ServiceNow", "CSA", I, "ServiceNow", 30),
    c("SNOW", "CAD", "ServiceNow Certified Application Developer Exam Prep", "ServiceNow", "CAD", I, "ServiceNow", 35),
    c("SNOW", "CISITSM", "ServiceNow Certified Implementation Specialist - IT Service Management Exam Prep", "ServiceNow", "CIS-ITSM", I, "ServiceNow", 35),
    c("SNOW", "CISHR", "ServiceNow Certified Implementation Specialist - HR Service Delivery Exam Prep", "ServiceNow", "CIS-HR", I, "ServiceNow", 30),
],
"FIN": (
    [c("ACCA", s, f"ACCA {n} ({s}) Exam Prep", "ACCA", s, lv, sub, h) for s, n, lv, sub, h in [
        ("BT", "Business and Technology", F, "ACCA Applied Knowledge", 40),
        ("MA", "Management Accounting", F, "ACCA Applied Knowledge", 40),
        ("FA", "Financial Accounting", F, "ACCA Applied Knowledge", 45),
        ("LW", "Corporate and Business Law", I, "ACCA Applied Skills", 45),
        ("PM", "Performance Management", I, "ACCA Applied Skills", 60),
        ("TX", "Taxation", I, "ACCA Applied Skills", 60),
        ("FR", "Financial Reporting", I, "ACCA Applied Skills", 70),
        ("AA", "Audit and Assurance", I, "ACCA Applied Skills", 60),
        ("FM", "Financial Management", I, "ACCA Applied Skills", 65),
        ("SBL", "Strategic Business Leader", A, "ACCA Strategic Professional", 70),
        ("SBR", "Strategic Business Reporting", A, "ACCA Strategic Professional", 75),
        ("AFM", "Advanced Financial Management", A, "ACCA Strategic Professional Options", 70),
        ("APM", "Advanced Performance Management", A, "ACCA Strategic Professional Options", 65),
        ("ATX", "Advanced Taxation", A, "ACCA Strategic Professional Options", 65),
        ("AAA", "Advanced Audit and Assurance", A, "ACCA Strategic Professional Options", 65)]]
    + [c("CPA", s, f"US CPA Exam: {n} ({s}) Prep", "AICPA & NASBA", s, A, sub, h) for s, n, sub, h in [
        ("AUD", "Auditing and Attestation", "US CPA Core", 90),
        ("FAR", "Financial Accounting and Reporting", "US CPA Core", 110),
        ("REG", "Taxation and Regulation", "US CPA Core", 90),
        ("BAR", "Business Analysis and Reporting", "US CPA Discipline", 85),
        ("ISC", "Information Systems and Controls", "US CPA Discipline", 70),
        ("TCP", "Tax Compliance and Planning", "US CPA Discipline", 70)]]
    + [
    c("CMA", "P1", "CMA Part 1: Financial Planning, Performance, and Analytics Prep", "IMA", "CMA Part 1", A, "CMA", 100),
    c("CMA", "P2", "CMA Part 2: Strategic Financial Management Prep", "IMA", "CMA Part 2", A, "CMA", 100),
    c("CIA", "P1", "CIA Part 1: Essentials of Internal Auditing Prep", "The IIA", "CIA Part 1", A, "CIA", 60),
    c("CIA", "P2", "CIA Part 2: Practice of Internal Auditing Prep", "The IIA", "CIA Part 2", A, "CIA", 55),
    c("CIA", "P3", "CIA Part 3: Business Knowledge for Internal Auditing Prep", "The IIA", "CIA Part 3", A, "CIA", 55),
    c("CFA", "L1", "CFA Program Level I Exam Prep", "CFA Institute", "CFA-L1", I, "CFA", 300),
    c("CFA", "L2", "CFA Program Level II Exam Prep", "CFA Institute", "CFA-L2", A, "CFA", 300),
    c("CFA", "L3", "CFA Program Level III Exam Prep", "CFA Institute", "CFA-L3", A, "CFA", 300),
    c("FRM", "P1", "FRM Exam Part I Prep", "GARP", "FRM Part I", A, "FRM", 200),
    c("FRM", "P2", "FRM Exam Part II Prep", "GARP", "FRM Part II", A, "FRM", 200),
    c("CAIA", "L1", "CAIA Level I Exam Prep", "CAIA Association", "CAIA Level I", A, "CAIA", 200),
    c("CAIA", "L2", "CAIA Level II Exam Prep", "CAIA Association", "CAIA Level II", A, "CAIA", 200),
    c("CFP", "EXAM", "CFP Certification Exam Prep", "CFP Board", "CFP", A, "Financial Planning", 150),
    c("EA", "P1", "IRS Enrolled Agent SEE Part 1: Individuals Prep", "IRS (Prometric)", "SEE Part 1", I, "Enrolled Agent", 50),
    c("EA", "P2", "IRS Enrolled Agent SEE Part 2: Businesses Prep", "IRS (Prometric)", "SEE Part 2", I, "Enrolled Agent", 50),
    c("EA", "P3", "IRS Enrolled Agent SEE Part 3: Representation, Practices and Procedures Prep", "IRS (Prometric)", "SEE Part 3", I, "Enrolled Agent", 40),
    ]
    + [c("CIMA", s, f"CIMA {n} ({s}) Exam Prep", "CIMA (AICPA & CIMA)", s, lv, sub, h) for s, n, lv, sub, h in [
        ("BA1", "Fundamentals of Business Economics", F, "CIMA Certificate in Business Accounting", 35),
        ("BA2", "Fundamentals of Management Accounting", F, "CIMA Certificate in Business Accounting", 35),
        ("BA3", "Fundamentals of Financial Accounting", F, "CIMA Certificate in Business Accounting", 35),
        ("BA4", "Fundamentals of Ethics, Corporate Governance and Business Law", F, "CIMA Certificate in Business Accounting", 30),
        ("E1", "Managing Finance in a Digital World", I, "CIMA Operational Level", 50),
        ("P1", "Management Accounting", I, "CIMA Operational Level", 55),
        ("F1", "Financial Reporting", I, "CIMA Operational Level", 55),
        ("OCS", "Operational Case Study", I, "CIMA Operational Level", 30),
        ("E2", "Managing Performance", A, "CIMA Management Level", 50),
        ("P2", "Advanced Management Accounting", A, "CIMA Management Level", 55),
        ("F2", "Advanced Financial Reporting", A, "CIMA Management Level", 60),
        ("MCS", "Management Case Study", A, "CIMA Management Level", 30),
        ("E3", "Strategic Management", A, "CIMA Strategic Level", 50),
        ("P3", "Risk Management", A, "CIMA Strategic Level", 50),
        ("F3", "Financial Strategy", A, "CIMA Strategic Level", 55),
        ("SCS", "Strategic Case Study", A, "CIMA Strategic Level", 30)]]
),
"PMB": [
    c("PMI", "PMP", "PMI Project Management Professional (PMP) Exam Prep", "PMI", "PMP", A, "PMI", 80),
    c("PMI", "CAPM", "PMI Certified Associate in Project Management (CAPM) Exam Prep", "PMI", "CAPM", F, "PMI", 35),
    c("PMI", "ACP", "PMI Agile Certified Practitioner (PMI-ACP) Exam Prep", "PMI", "PMI-ACP", I, "PMI", 40),
    c("PMI", "RMP", "PMI Risk Management Professional (PMI-RMP) Exam Prep", "PMI", "PMI-RMP", A, "PMI", 40),
    c("PMI", "SP", "PMI Scheduling Professional (PMI-SP) Exam Prep", "PMI", "PMI-SP", A, "PMI", 40),
    c("PMI", "PBA", "PMI Professional in Business Analysis (PMI-PBA) Exam Prep", "PMI", "PMI-PBA", A, "PMI", 40),
    c("PMI", "PGMP", "PMI Program Management Professional (PgMP) Exam Prep", "PMI", "PgMP", A, "PMI", 50),
    c("PMI", "PFMP", "PMI Portfolio Management Professional (PfMP) Exam Prep", "PMI", "PfMP", A, "PMI", 50),
    c("PX", "P2F", "PRINCE2 Foundation Exam Prep", "PeopleCert / AXELOS", "PRINCE2 Foundation", F, "PRINCE2", 20),
    c("PX", "P2P", "PRINCE2 Practitioner Exam Prep", "PeopleCert / AXELOS", "PRINCE2 Practitioner", I, "PRINCE2", 25),
    c("PX", "P2AF", "PRINCE2 Agile Foundation Exam Prep", "PeopleCert / AXELOS", "PRINCE2 Agile Foundation", F, "PRINCE2", 18),
    c("PX", "P2AP", "PRINCE2 Agile Practitioner Exam Prep", "PeopleCert / AXELOS", "PRINCE2 Agile Practitioner", I, "PRINCE2", 22),
    c("PX", "MSPF", "MSP Foundation Exam Prep", "PeopleCert / AXELOS", "MSP Foundation", I, "PRINCE2", 18),
    c("ITIL", "ITIL4F", "ITIL 4 Foundation Exam Prep", "PeopleCert / AXELOS", "ITIL 4 Foundation", F, "ITIL", 20),
    c("ITIL", "CDS", "ITIL 4 Specialist: Create, Deliver and Support Exam Prep", "PeopleCert / AXELOS", "ITIL 4 CDS", I, "ITIL", 25),
    c("ITIL", "DSV", "ITIL 4 Specialist: Drive Stakeholder Value Exam Prep", "PeopleCert / AXELOS", "ITIL 4 DSV", I, "ITIL", 22),
    c("ITIL", "HVIT", "ITIL 4 Specialist: High-velocity IT Exam Prep", "PeopleCert / AXELOS", "ITIL 4 HVIT", I, "ITIL", 22),
    c("ITIL", "DPI", "ITIL 4 Strategist: Direct, Plan and Improve Exam Prep", "PeopleCert / AXELOS", "ITIL 4 DPI", I, "ITIL", 22),
    c("LSS", "WB", "Lean Six Sigma White Belt", "Vendor-neutral (body varies)", "", F, "Lean Six Sigma", 8),
    c("LSS", "YB", "Lean Six Sigma Yellow Belt Exam Prep (ASQ CSSYB-aligned)", "ASQ", "CSSYB", F, "Lean Six Sigma", 20),
    c("LSS", "GB", "Lean Six Sigma Green Belt Exam Prep (ASQ CSSGB-aligned)", "ASQ", "CSSGB", I, "Lean Six Sigma", 50),
    c("LSS", "BB", "Lean Six Sigma Black Belt Exam Prep (ASQ CSSBB-aligned)", "ASQ", "CSSBB", A, "Lean Six Sigma", 80),
    c("LSS", "MBB", "Lean Six Sigma Master Black Belt Exam Prep (ASQ CMBB-aligned)", "ASQ", "CMBB", A, "Lean Six Sigma", 60),
    c("IIBA", "ECBA", "IIBA ECBA Exam Prep", "IIBA", "ECBA", F, "IIBA", 30),
    c("IIBA", "CCBA", "IIBA CCBA Exam Prep", "IIBA", "CCBA", I, "IIBA", 40),
    c("IIBA", "CBAP", "IIBA CBAP Exam Prep", "IIBA", "CBAP", A, "IIBA", 50),
    c("SCRUM", "PSM1", "Scrum.org Professional Scrum Master I (PSM I) Prep", "Scrum.org", "PSM I", F, "Scrum", 15),
    c("SCRUM", "PSM2", "Scrum.org Professional Scrum Master II (PSM II) Prep", "Scrum.org", "PSM II", I, "Scrum", 20),
    c("SCRUM", "PSPO1", "Scrum.org Professional Scrum Product Owner I (PSPO I) Prep", "Scrum.org", "PSPO I", F, "Scrum", 15),
    c("SCRUM", "PSPO2", "Scrum.org Professional Scrum Product Owner II (PSPO II) Prep", "Scrum.org", "PSPO II", I, "Scrum", 20),
    c("SCRUM", "CSM", "Scrum Alliance Certified ScrumMaster (CSM) Knowledge Prep", "Scrum Alliance", "CSM", F, "Scrum", 16),
    c("SCRUM", "CSPO", "Scrum Alliance Certified Scrum Product Owner (CSPO) Knowledge Prep", "Scrum Alliance", "CSPO", F, "Scrum", 16),
    c("SAFE", "SA", "SAFe Agilist (Leading SAFe) Knowledge Prep", "Scaled Agile", "SA", I, "Scaled Agile", 16),
],
"HLT": [
    c("NCSBN", "NCLEXRN", "NCLEX-RN Exam Prep", "NCSBN", "NCLEX-RN", I, "Nursing Licensure", 120),
    c("NCSBN", "NCLEXPN", "NCLEX-PN Exam Prep", "NCSBN", "NCLEX-PN", I, "Nursing Licensure", 100),
    c("USMLE", "STEP1", "USMLE Step 1 Exam Prep", "FSMB & NBME", "USMLE Step 1", A, "Medical Licensure", 300),
    c("USMLE", "STEP2", "USMLE Step 2 CK Exam Prep", "FSMB & NBME", "USMLE Step 2 CK", A, "Medical Licensure", 250),
    c("USMLE", "STEP3", "USMLE Step 3 Exam Prep", "FSMB & NBME", "USMLE Step 3", A, "Medical Licensure", 200),
    c("NCCPA", "PANCE", "PANCE (Physician Assistant) Exam Prep", "NCCPA", "PANCE", A, "Licensure", 150),
    c("NABP", "NAPLEX", "NAPLEX Exam Prep", "NABP", "NAPLEX", A, "Pharmacy", 150),
    c("PTCB", "PTCE", "Pharmacy Technician Certification Exam (PTCE) Prep", "PTCB", "PTCE", F, "Pharmacy", 50),
    c("AAPC", "CPC", "AAPC Certified Professional Coder (CPC) Exam Prep", "AAPC", "CPC", I, "Health Information", 80),
    c("AHIMA", "CCS", "AHIMA Certified Coding Specialist (CCS) Exam Prep", "AHIMA", "CCS", I, "Health Information", 70),
    c("AHIMA", "RHIT", "AHIMA RHIT Exam Prep", "AHIMA", "RHIT", I, "Health Information", 70),
    c("AAMA", "CMAAAMA", "AAMA Certified Medical Assistant (CMA) Exam Prep", "AAMA", "CMA (AAMA)", F, "Allied Health", 60),
    c("BCEN", "CEN", "Certified Emergency Nurse (CEN) Exam Prep", "BCEN", "CEN", A, "Nursing Specialty", 60),
    c("AACN", "CCRN", "CCRN (Adult) Exam Prep", "AACN Certification Corporation", "CCRN", A, "Nursing Specialty", 70),
    c("AANP", "FNP", "AANPCB Family Nurse Practitioner (FNP) Exam Prep", "AANPCB", "FNP", A, "Nursing Specialty", 100),
    c("NREMT", "EMT", "NREMT EMT Cognitive Exam Prep", "NREMT", "EMT", F, "Emergency Medical Services", 60),
],
"ENG": [
    c("ASCM", "CPIM", "ASCM CPIM Exam Prep", "ASCM (APICS)", "CPIM", I, "Supply Chain", 80),
    c("ASCM", "CSCP", "ASCM CSCP Exam Prep", "ASCM (APICS)", "CSCP", A, "Supply Chain", 80),
    c("ASCM", "CLTD", "ASCM CLTD Exam Prep", "ASCM (APICS)", "CLTD", A, "Supply Chain", 70),
    c("ISM", "CPSM", "ISM CPSM Exam Prep", "Institute for Supply Management", "CPSM", A, "Procurement", 70),
    c("CIPS", "L4", "CIPS Level 4 Diploma in Procurement and Supply Knowledge Prep", "CIPS", "", I, "Procurement", 60),
    c("NCEES", "FECIV", "NCEES FE Civil Exam Prep", "NCEES", "FE Civil", I, "Engineering Licensure", 150),
    c("NCEES", "FEMEC", "NCEES FE Mechanical Exam Prep", "NCEES", "FE Mechanical", I, "Engineering Licensure", 150),
    c("NCEES", "FEELE", "NCEES FE Electrical and Computer Exam Prep", "NCEES", "FE Electrical and Computer", I, "Engineering Licensure", 150),
    c("NCEES", "FECHE", "NCEES FE Chemical Exam Prep", "NCEES", "FE Chemical", I, "Engineering Licensure", 150),
    c("NCEES", "FEIND", "NCEES FE Industrial and Systems Exam Prep", "NCEES", "FE Industrial and Systems", I, "Engineering Licensure", 150),
    c("NCEES", "FEENV", "NCEES FE Environmental Exam Prep", "NCEES", "FE Environmental", I, "Engineering Licensure", 150),
    c("NCEES", "FEOTH", "NCEES FE Other Disciplines Exam Prep", "NCEES", "FE Other Disciplines", I, "Engineering Licensure", 150),
    c("ASQ", "CQE", "ASQ Certified Quality Engineer (CQE) Exam Prep", "ASQ", "CQE", A, "Quality", 80),
    c("ASQ", "CQA", "ASQ Certified Quality Auditor (CQA) Exam Prep", "ASQ", "CQA", A, "Quality", 70),
    c("ASQ", "CRE", "ASQ Certified Reliability Engineer (CRE) Exam Prep", "ASQ", "CRE", A, "Quality", 80),
    c("ASQ", "CMQOE", "ASQ Certified Manager of Quality/Organizational Excellence Exam Prep", "ASQ", "CMQ/OE", A, "Quality", 70),
    c("USGBC", "LEEDGA", "LEED Green Associate Exam Prep", "USGBC / GBCI", "LEED GA", F, "Sustainable Building", 30),
    c("DS", "CSWA", "SOLIDWORKS CSWA Knowledge Prep", "Dassault Systemes", "CSWA", F, "CAD", 30),
    c("ADSK", "ACUCAD", "Autodesk Certified User: AutoCAD Knowledge Prep", "Autodesk", "", F, "CAD", 30),
    c("SMRP", "CMRP", "SMRP CMRP Exam Prep", "SMRP", "CMRP", A, "Maintenance & Reliability", 50),
],
"BUS": [
    c("SFDC", "ADM", "Salesforce Certified Platform Administrator Exam Prep", "Salesforce", "", F, "Salesforce", 40),
    c("SFDC", "ADVADM", "Salesforce Certified Platform Administrator II (Advanced) Exam Prep", "Salesforce", "", I, "Salesforce", 40),
    c("SFDC", "PAB", "Salesforce Certified Platform App Builder Exam Prep", "Salesforce", "", I, "Salesforce", 40),
    c("SFDC", "AIA", "Salesforce Certified AI Associate Exam Prep", "Salesforce", "", F, "Salesforce", 15),
    c("SFDC", "AGENTF", "Salesforce Certified Agentforce Specialist Exam Prep", "Salesforce", "", I, "Salesforce", 25),
    c("SFDC", "BA", "Salesforce Certified Business Analyst Exam Prep", "Salesforce", "", I, "Salesforce", 30),
    c("SFDC", "MCE", "Salesforce Certified Marketing Cloud Email Specialist Exam Prep", "Salesforce", "", I, "Salesforce", 30),
    c("SFDC", "SCC", "Salesforce Certified Sales Cloud Consultant Exam Prep", "Salesforce", "", I, "Salesforce", 35),
    c("SFDC", "SVCC", "Salesforce Certified Service Cloud Consultant Exam Prep", "Salesforce", "", I, "Salesforce", 35),
    c("SAP", "S4FIN", "SAP Certified Associate - SAP S/4HANA Cloud Private Edition, Financial Accounting Prep", "SAP", "", I, "SAP", 50),
    c("SAP", "S4MM", "SAP Certified Associate - SAP S/4HANA Sourcing and Procurement Prep", "SAP", "", I, "SAP", 50),
    c("SAP", "S4SD", "SAP Certified Associate - SAP S/4HANA Sales Prep", "SAP", "", I, "SAP", 50),
    c("SAP", "S4PP", "SAP Certified Associate - SAP S/4HANA Production Planning and Manufacturing Prep", "SAP", "", I, "SAP", 50),
    c("SAP", "ABAP", "SAP Certified Associate - Back-End Developer - ABAP Cloud Prep", "SAP", "", I, "SAP", 50),
    c("SAP", "BTP", "SAP Certified Associate - SAP Business Technology Platform Prep", "SAP", "", I, "SAP", 40),
    c("SHRM", "CP", "SHRM-CP Exam Prep", "SHRM", "SHRM-CP", I, "Human Resources", 60),
    c("SHRM", "SCP", "SHRM-SCP Exam Prep", "SHRM", "SHRM-SCP", A, "Human Resources", 60),
    c("HRCI", "APHR", "HRCI aPHR Exam Prep", "HRCI", "aPHR", F, "Human Resources", 35),
    c("HRCI", "PHR", "HRCI PHR Exam Prep", "HRCI", "PHR", I, "Human Resources", 55),
    c("HRCI", "SPHR", "HRCI SPHR Exam Prep", "HRCI", "SPHR", A, "Human Resources", 55),
    c("HUB", "INBOUND", "HubSpot Inbound Marketing Certification Prep", "HubSpot Academy", "", F, "Marketing Platforms", 8),
],
"LNG": [
    c("IELTS", "AC", "IELTS Academic Preparation (MCQ-assessable skills)", "British Council / IDP / Cambridge", "IELTS-AC", I, "English Testing", 60),
    c("IELTS", "GT", "IELTS General Training Preparation (MCQ-assessable skills)", "British Council / IDP / Cambridge", "IELTS-GT", I, "English Testing", 55),
    c("ETS", "TOEFL", "TOEFL iBT Preparation (MCQ-assessable skills)", "ETS", "TOEFL iBT", I, "English Testing", 60),
    c("PEARSON", "PTEA", "PTE Academic Preparation (MCQ-assessable skills)", "Pearson", "PTE Academic", I, "English Testing", 50),
    c("PEARSON", "PTEC", "PTE Core Preparation (MCQ-assessable skills)", "Pearson", "PTE Core", I, "English Testing", 45),
    c("OET", "NUR", "OET Nursing Preparation (MCQ-assessable skills)", "OET (Cambridge Boxhill)", "OET Nursing", I, "English Testing", 50),
    c("OET", "MED", "OET Medicine Preparation (MCQ-assessable skills)", "OET (Cambridge Boxhill)", "OET Medicine", I, "English Testing", 50),
    c("DUO", "DET", "Duolingo English Test Preparation (MCQ-assessable skills)", "Duolingo", "DET", I, "English Testing", 30),
    c("CAM", "B2F", "Cambridge B2 First Preparation (MCQ-assessable skills)", "Cambridge English", "B2 First", I, "English Testing", 50),
    c("CAM", "C1A", "Cambridge C1 Advanced Preparation (MCQ-assessable skills)", "Cambridge English", "C1 Advanced", A, "English Testing", 55),
    c("CAM", "C2P", "Cambridge C2 Proficiency Preparation (MCQ-assessable skills)", "Cambridge English", "C2 Proficiency", A, "English Testing", 60),
    c("JLPT", "N5", "JLPT N5 Preparation", "Japan Foundation / JEES", "JLPT N5", F, "Japanese", 60),
    c("JLPT", "N4", "JLPT N4 Preparation", "Japan Foundation / JEES", "JLPT N4", F, "Japanese", 80),
    c("JLPT", "N3", "JLPT N3 Preparation", "Japan Foundation / JEES", "JLPT N3", I, "Japanese", 100),
    c("JLPT", "N2", "JLPT N2 Preparation", "Japan Foundation / JEES", "JLPT N2", A, "Japanese", 120),
    c("JLPT", "N1", "JLPT N1 Preparation", "Japan Foundation / JEES", "JLPT N1", A, "Japanese", 150),
    c("HSK", "H1", "HSK 1 Preparation", "Chinese Testing International", "HSK 1", F, "Chinese", 40),
    c("HSK", "H2", "HSK 2 Preparation", "Chinese Testing International", "HSK 2", F, "Chinese", 50),
    c("HSK", "H3", "HSK 3 Preparation", "Chinese Testing International", "HSK 3", I, "Chinese", 70),
    c("HSK", "H4", "HSK 4 Preparation", "Chinese Testing International", "HSK 4", I, "Chinese", 90),
    c("TOPIK", "T1", "TOPIK I Preparation", "NIIED", "TOPIK I", F, "Korean", 60),
    c("TOPIK", "T2", "TOPIK II Preparation", "NIIED", "TOPIK II", I, "Korean", 100),
    c("FEI", "DELFB1", "DELF B1 Preparation (MCQ-assessable skills)", "France Education International", "DELF B1", I, "French", 70),
    c("FEI", "DELFB2", "DELF B2 Preparation (MCQ-assessable skills)", "France Education International", "DELF B2", I, "French", 80),
    c("IC", "DELEB1", "DELE B1 Preparation (MCQ-assessable skills)", "Instituto Cervantes", "DELE B1", I, "Spanish", 70),
    c("GI", "GB1", "Goethe-Zertifikat B1 Preparation (MCQ-assessable skills)", "Goethe-Institut", "Goethe B1", I, "German", 70),
],
"CRE": [
    c("ADOBE", "PS", "Adobe Certified Professional in Visual Design using Photoshop Knowledge Prep", "Adobe", "", F, "Adobe", 25),
    c("ADOBE", "AI", "Adobe Certified Professional in Graphic Design & Illustration using Illustrator Knowledge Prep", "Adobe", "", F, "Adobe", 25),
    c("ADOBE", "PR", "Adobe Certified Professional in Digital Video using Premiere Pro Knowledge Prep", "Adobe", "", F, "Adobe", 25),
    c("ADOBE", "AE", "Adobe Certified Professional in Visual Effects & Motion Graphics using After Effects Knowledge Prep", "Adobe", "", I, "Adobe", 25),
    c("ADOBE", "ID", "Adobe Certified Professional in Print & Digital Media Publication using InDesign Knowledge Prep", "Adobe", "", F, "Adobe", 20),
    c("UNITY", "UCU", "Unity Certified User: Programmer Knowledge Prep", "Unity", "", F, "Game Development", 25),
],
}

# Non-certification skills / foundation courses, (subcategory, level, hours, [titles])
SKILLS = {
"AI": [
    ("AI Foundations", F, 10, ["What Is Artificial Intelligence? A Non-Technical Introduction", "AI for Everyone: Concepts, Capabilities and Limits", "History and Milestones of AI", "Mathematics for AI: Linear Algebra Essentials", "Mathematics for AI: Probability and Statistics", "Mathematics for AI: Calculus and Optimisation", "Data Literacy for AI", "AI Terminology and Glossary Mastery", "AI in Society: Risks, Benefits and Myths", "Choosing AI Tools for Work"]),
    ("Machine Learning", I, 20, ["Machine Learning Fundamentals", "Supervised Learning: Regression", "Supervised Learning: Classification", "Unsupervised Learning and Clustering", "Feature Engineering", "Model Evaluation and Validation", "Decision Trees and Ensemble Methods", "Support Vector Machines", "Dimensionality Reduction (PCA, t-SNE, UMAP)", "Time Series Forecasting with ML", "Recommender Systems", "Anomaly Detection", "Bayesian Machine Learning", "Reinforcement Learning Fundamentals", "Scikit-learn in Practice", "Imbalanced Data Techniques", "Hyperparameter Tuning", "Interpretable ML and Explainability (SHAP, LIME)", "AutoML Concepts", "Causal Inference for ML"]),
    ("Deep Learning", A, 25, ["Neural Networks from Scratch", "Deep Learning with PyTorch", "Deep Learning with TensorFlow and Keras", "Convolutional Neural Networks", "Recurrent Networks and Sequence Models", "Transformers Architecture Explained", "Attention Mechanisms in Depth", "Optimisers, Regularisation and Training Stability", "Transfer Learning", "Self-Supervised Learning", "Graph Neural Networks", "Diffusion Models", "Generative Adversarial Networks", "Variational Autoencoders", "Distributed Training at Scale", "Model Compression and Quantisation"]),
    ("Generative AI & LLMs", I, 15, ["Large Language Models: How They Work", "Prompt Engineering Fundamentals", "Advanced Prompt Engineering Patterns", "Retrieval-Augmented Generation (RAG)", "Vector Databases and Embeddings", "Fine-Tuning LLMs (LoRA, PEFT)", "Evaluating LLM Applications", "LLM Application Security (Prompt Injection, Data Leakage)", "Building AI Agents", "Multi-Agent Systems Design", "Tool Use and Function Calling", "Model Context Protocol (MCP) Fundamentals", "LLM Observability and Monitoring", "Cost and Latency Optimisation for LLM Apps", "Open-Weight Models: Selection and Deployment", "Multimodal Models: Vision and Language", "Speech AI: ASR and TTS", "Synthetic Data Generation", "Guardrails and Content Safety", "Structured Output and Extraction with LLMs", "Long-Context Strategies", "Generative AI for Images", "Generative AI for Video and Audio", "Building Chatbots End to End", "AI Coding Assistants for Developers"]),
    ("MLOps & Engineering", A, 20, ["MLOps Fundamentals", "ML Pipelines and Orchestration", "Experiment Tracking and Model Registry", "Feature Stores", "Model Serving and Inference Optimisation", "Monitoring Models in Production (Drift)", "CI/CD for Machine Learning", "LLMOps", "Edge AI and On-Device Inference", "GPU Computing Fundamentals for AI", "Data Labelling and Annotation Operations", "AI System Design Interviews"]),
    ("Computer Vision & NLP", I, 20, ["Computer Vision Fundamentals", "Object Detection and Segmentation", "OCR and Document AI", "Video Analytics", "Natural Language Processing Fundamentals", "Text Classification and Sentiment Analysis", "Named Entity Recognition and Information Extraction", "Machine Translation", "Topic Modelling", "Search and Ranking with ML"]),
    ("Responsible AI & Governance", I, 12, ["Responsible AI Principles", "AI Ethics and Fairness", "AI Risk Management Frameworks (NIST AI RMF overview)", "EU AI Act Overview for Practitioners", "AI Governance Programmes in Organisations", "Privacy-Preserving Machine Learning", "AI Auditing Fundamentals", "Bias Detection and Mitigation", "AI Incident Management", "Model Cards and AI Documentation", "AI Red Teaming Fundamentals", "Copyright and IP Issues in Generative AI"]),
    ("Applied AI by Function", F, 8, ["AI for Marketing", "AI for Sales", "AI for Finance Professionals", "AI for Accountants and Auditors", "AI for HR and Recruiting", "AI for Healthcare Professionals", "AI for Educators", "AI for Lawyers and Legal Operations", "AI for Customer Service", "AI for Supply Chain", "AI for Project Managers", "AI for Product Managers", "AI for Small Business Owners", "AI for Software Testers", "AI for Data Analysts", "AI Productivity for Office Workers", "AI for Content Creators", "AI for Researchers and Academic Writing", "AI Strategy for Executives", "AI Product Management", "AI Business Case and ROI", "AI Change Management and Adoption", "AI for Cybersecurity Defenders", "AI in Manufacturing", "AI in Retail and E-commerce", "AI in Banking and Insurance", "AI in Logistics", "AI for Real Estate", "AI for Nonprofits", "AI for Government and Public Sector", "AI for Students: Study Smarter", "Automation with AI and No-Code Tools", "AI for Spreadsheet Power Users", "AI for Presentations and Documents", "AI Literacy for Managers", "AI Use Policy Writing for Organisations", "Evaluating AI Vendors", "AI in Customer Experience Design", "Conversational AI Design", "AI for Journalists and Fact-Checking", "AI in Agriculture", "AI in Energy and Utilities", "AI in Telecommunications", "AI for Game Development", "AI and the Future of Work", "AI for Nurses and Allied Health", "AI for Pharmacists", "AI for Engineers (CAE and Design)", "AI for Translators and Localisation", "AI for Architects and Construction", "AI in Media and Entertainment", "AI for Startups", "AI in Insurance Underwriting", "AI-Assisted Data Visualisation", "AI for Fraud Detection Teams"]),
],
"MIC": [
    ("Microsoft Skills", F, 10, ["Excel Fundamentals", "Excel Formulas and Functions", "Excel PivotTables and Data Analysis", "Excel Power Query", "Excel Dynamic Arrays and LAMBDA", "Excel Financial Modelling Basics", "Power BI Desktop Fundamentals", "DAX Fundamentals", "Power BI Data Modelling", "Power Automate Cloud Flows Basics", "Power Apps Canvas Apps Basics", "Microsoft 365 Copilot for Productivity", "Copilot Studio: Building Agents", "Microsoft Teams for Collaboration", "SharePoint Online for Site Owners", "Word for Professional Documents", "PowerPoint for Effective Presentations", "Outlook Productivity", "Microsoft Entra ID Essentials", "Microsoft Intune Essentials", "PowerShell for Microsoft 365 Administration", "Azure CLI and Bicep Essentials", "Azure Networking Essentials", "Azure Cost Management Essentials", "Microsoft Fabric Fundamentals", "Microsoft Purview Essentials", "Microsoft Sentinel Essentials", "Windows 11 for IT Support", "Windows Server Administration Basics", "Microsoft Defender XDR Essentials", "Azure Kubernetes Service Essentials", "Azure Functions and Serverless Essentials", "Azure Landing Zones and Well-Architected Framework", "Azure Monitor and Log Analytics with KQL", "KQL (Kusto Query Language) Fundamentals", "Access Database Fundamentals", "Microsoft Project Fundamentals", "Visio for Process Diagrams", "OneNote and Loop for Knowledge Work", "Microsoft Forms and Lists", "Dataverse Fundamentals", "Power Pages Fundamentals", "Azure DevOps Boards and Repos", "Azure OpenAI in Foundry Essentials", "Microsoft Viva Overview", "Exchange Online Administration Basics", "Azure Storage Deep Dive", "Azure SQL Database Essentials", "Azure Virtual Machines Deep Dive", "Hybrid Identity with Entra Connect"]),
],
"AWS": [
    ("AWS Skills", I, 12, ["AWS Cloud Essentials for Beginners", "AWS IAM Deep Dive", "Amazon EC2 Deep Dive", "Amazon S3 Deep Dive", "Amazon VPC Networking", "AWS Lambda and Serverless", "Amazon RDS and Aurora", "Amazon DynamoDB", "AWS CloudFormation", "AWS CDK", "Amazon ECS and Fargate", "Amazon EKS", "AWS Well-Architected Framework", "AWS Cost Optimisation", "Amazon CloudWatch and Observability", "AWS Security Services Overview", "AWS KMS and Encryption", "AWS Organizations and Control Tower", "Amazon Route 53 and CloudFront", "AWS Messaging: SQS, SNS, EventBridge", "AWS Step Functions", "Amazon Kinesis and Streaming", "AWS Glue and Data Lakes", "Amazon Redshift", "Amazon Athena", "Amazon SageMaker AI Fundamentals", "Amazon Bedrock and Generative AI", "Amazon Q for Developers", "AWS Migration Strategies", "AWS Backup and Disaster Recovery", "AWS Hybrid Networking (VPN, Direct Connect)", "AWS DevOps CI/CD Tools", "AWS Systems Manager", "AWS Billing and Pricing Essentials", "AWS Identity Center and Federation", "Amazon API Gateway", "AWS Architecture Case Studies", "Amazon QuickSight", "AWS IoT Fundamentals", "AWS for Startups", "AWS Containers Security", "AWS Multi-Account Strategy", "AWS Data Engineering Pipelines", "AWS Serverless Application Patterns", "AWS Generative AI Application Patterns", "AWS Networking Deep Dive", "AWS Compliance and Governance Essentials"]),
],
"GCP": [
    ("Google Skills", I, 12, ["Google Cloud Essentials for Beginners", "Google Cloud IAM", "Compute Engine Deep Dive", "Google Kubernetes Engine", "Cloud Run and Serverless", "BigQuery Fundamentals", "BigQuery ML", "Vertex AI Fundamentals", "Gemini for Google Cloud", "Cloud Storage Deep Dive", "VPC Networking on Google Cloud", "Cloud SQL, Spanner and AlloyDB", "Dataflow and Pub/Sub", "Looker Fundamentals", "Looker Studio Dashboards", "Google Cloud Security Fundamentals", "Terraform on Google Cloud", "Google Cloud Cost Management", "Google Workspace Productivity", "Google Sheets for Data Analysis", "Apps Script Automation", "Firebase for App Developers", "Android Development Fundamentals with Kotlin", "Google Analytics 4 Implementation", "Google Tag Manager", "Google Search Console and SEO Basics", "Google Ads Campaign Management", "YouTube Analytics for Creators", "Google Cloud Architecture Framework", "Anthos and Hybrid Cloud Concepts", "Gemini Apps for Workplace Productivity", "Google Cloud Operations Suite", "Apigee API Management Basics", "Dataproc and Spark on Google Cloud", "Google Cloud Migration Strategies", "Chrome Enterprise Administration Basics", "Google Cloud for Startups", "Google Cloud Identity and Access Management Deep Dive", "Google Cloud Data Analytics Pipelines", "Google Cloud Generative AI Application Patterns"]),
],
"PRG": [
    ("Programming Languages", F, 30, ["Programming Fundamentals (Language-Agnostic)", "Python for Beginners", "Intermediate Python", "Advanced Python", "JavaScript Fundamentals", "Modern JavaScript (ES2015+)", "TypeScript Fundamentals", "Java Fundamentals", "Advanced Java", "C Programming", "C++ Programming Fundamentals", "Modern C++", "C# Fundamentals", "Go Fundamentals", "Rust Fundamentals", "Kotlin Fundamentals", "Swift Fundamentals", "PHP Fundamentals", "Ruby Fundamentals", "R Programming", "Scala Fundamentals", "Dart Fundamentals", "Bash Scripting", "PowerShell Scripting", "Julia for Scientific Computing", "Elixir Fundamentals", "Haskell and Functional Programming", "Lua Fundamentals", "MATLAB Fundamentals", "Assembly Language Basics", "Perl Fundamentals", "Objective-C Essentials", "SQL for Developers", "Regex Mastery", "Zig Fundamentals"]),
    ("Computer Science", I, 25, ["Data Structures", "Algorithms", "Algorithm Design and Analysis", "Discrete Mathematics for CS", "Operating Systems Concepts", "Computer Networks for Developers", "Computer Architecture", "Compilers and Interpreters", "Databases Internals", "Distributed Systems", "Concurrency and Parallel Programming", "Theory of Computation", "Cryptography for Developers", "Competitive Programming", "Coding Interview Preparation"]),
    ("Web Development", I, 25, ["HTML and CSS Fundamentals", "Responsive Web Design", "Web Accessibility (WCAG)", "React Fundamentals", "Advanced React", "Next.js", "Vue.js", "Angular", "Svelte", "Node.js Fundamentals", "Express.js APIs", "Django", "Flask and FastAPI", "Spring Boot", "ASP.NET Core", "Laravel", "Ruby on Rails", "REST API Design", "GraphQL", "WebSockets and Real-Time Apps", "Web Performance Optimisation", "Web Security for Developers (OWASP Top 10)", "Progressive Web Apps", "Tailwind CSS", "Browser Internals for Developers", "Web Components"]),
    ("Mobile Development", I, 25, ["Android with Jetpack Compose", "iOS with SwiftUI", "Flutter", "React Native", "Mobile App Architecture", "Mobile App Testing", "Mobile App Security"]),
    ("Software Engineering", I, 20, ["Git and GitHub Fundamentals", "Object-Oriented Design", "Design Patterns", "Clean Code", "Refactoring", "Software Architecture Fundamentals", "Microservices Architecture", "Domain-Driven Design", "Event-Driven Architecture", "System Design Fundamentals", "System Design for Scale", "Unit Testing and TDD", "Test Automation with Selenium and Playwright", "API Testing", "Performance Testing", "ISTQB Foundation-Aligned Software Testing Concepts", "Secure Software Development", "Code Review Practices", "Technical Documentation for Developers", "Software Estimation", "Agile Engineering Practices", "Open Source Contribution"]),
    ("DevOps & Cloud Native", I, 20, ["Linux Command Line", "Linux System Administration", "Docker Fundamentals", "Kubernetes Fundamentals", "Helm and Kubernetes Packaging", "CI/CD Pipelines", "GitHub Actions in Practice", "Jenkins", "Terraform Fundamentals", "Ansible", "Infrastructure as Code Patterns", "Observability: Logs, Metrics, Traces", "Prometheus and Grafana", "Site Reliability Engineering", "Platform Engineering", "GitOps with Argo CD", "Service Mesh Fundamentals", "Serverless Architecture", "DevSecOps", "Nginx and Web Servers"]),
    ("Game & Specialised Development", I, 25, ["Unity Game Development", "Unreal Engine Fundamentals", "Godot Game Development", "Embedded Systems Programming", "Arduino and Microcontrollers", "Raspberry Pi Projects", "Blockchain and Smart Contracts", "Solidity Fundamentals", "Quantum Computing Fundamentals", "WebAssembly", "High-Performance Computing", "Low-Code Development"]),
],
"DAT": [
    ("Data Skills", I, 20, ["Data Analysis Fundamentals", "Statistics for Data Analysis", "SQL Fundamentals", "Advanced SQL", "PostgreSQL", "MySQL", "SQL Server and T-SQL", "MongoDB", "Redis", "Cassandra and Wide-Column Stores", "Neo4j and Graph Databases", "Data Modelling", "Dimensional Modelling and Data Warehousing", "ETL and ELT Design", "dbt Fundamentals", "Apache Spark", "PySpark", "Apache Kafka", "Apache Airflow", "Data Lakehouse Architecture", "Delta Lake and Apache Iceberg", "Data Quality Engineering", "Data Governance Fundamentals", "Master Data Management", "Data Catalogs and Lineage", "Data Privacy Engineering", "Pandas for Data Analysis", "NumPy", "Data Visualisation Principles", "Matplotlib and Seaborn", "Plotly and Dash", "Tableau Desktop Skills", "Power BI for Analysts", "Looker and LookML", "Qlik Sense", "Excel for Data Analysis", "Business Intelligence Fundamentals", "Data Storytelling", "A/B Testing and Experimentation", "Product Analytics", "Marketing Analytics", "Financial Data Analysis", "Healthcare Data Analytics", "Supply Chain Analytics", "HR and People Analytics", "Web Analytics", "Geospatial Data Analysis", "Time Series Analysis", "Survey Design and Analysis", "Econometrics Fundamentals", "Data Science Fundamentals", "Data Science Project Lifecycle", "Big Data Fundamentals", "Data Engineering Fundamentals", "Data Mesh Concepts", "Data Strategy for Leaders", "Data Ethics", "Analytics Engineering", "Streaming Analytics", "SAS Programming Fundamentals", "Snowflake for Analysts", "Databricks Lakehouse Fundamentals"]),
],
"CYB": [
    ("Cyber & IT Skills", I, 15, ["Cybersecurity Fundamentals", "Networking Fundamentals", "TCP/IP Deep Dive", "IT Support Fundamentals", "Help Desk and Customer Support", "Windows Administration for IT", "Active Directory Fundamentals", "Network Security", "Firewall Concepts and Configuration", "Wireless Security", "Security Operations Centre (SOC) Fundamentals", "SIEM and Log Analysis", "Incident Response", "Digital Forensics Fundamentals", "Malware Analysis Fundamentals", "Threat Intelligence", "Threat Hunting", "Vulnerability Management", "Penetration Testing Fundamentals", "Web Application Penetration Testing", "Cloud Security Fundamentals", "Identity and Access Management", "Zero Trust Architecture", "Cryptography Fundamentals", "Security Governance, Risk and Compliance", "ISO/IEC 27001 Fundamentals", "NIST Cybersecurity Framework", "Data Protection and GDPR Essentials", "PCI DSS Essentials", "Business Continuity and Disaster Recovery", "Security Awareness for Employees", "Phishing and Social Engineering Defence", "OT and ICS Security Fundamentals", "Mobile Device Security", "Endpoint Security", "Email Security", "DNS and PKI Essentials", "Virtualisation Fundamentals", "Storage and Backup Fundamentals", "IT Asset Management", "Network Troubleshooting", "IPv6 Fundamentals", "SD-WAN Concepts", "Cloud Networking Fundamentals", "Security Architecture Fundamentals", "Privileged Access Management", "Ransomware Defence and Recovery", "Secure Configuration and Hardening"]),
],
"FIN": [
    ("Finance & Accounting Skills", F, 15, ["Accounting Fundamentals", "Bookkeeping Essentials", "Financial Statements Analysis", "Managerial Accounting", "Cost Accounting", "Corporate Finance Fundamentals", "Financial Modelling in Excel", "Valuation Fundamentals (DCF, Comparables)", "Budgeting and Forecasting", "IFRS Fundamentals", "US GAAP Fundamentals", "Auditing Fundamentals", "Internal Controls and SOX", "Tax Fundamentals (Conceptual)", "Personal Finance", "Investment Fundamentals", "Fixed Income Fundamentals", "Equity Markets Fundamentals", "Derivatives Fundamentals", "Portfolio Management Fundamentals", "Risk Management Fundamentals", "Banking Fundamentals", "Credit Analysis", "Treasury Management", "FP&A Essentials", "Mergers and Acquisitions Fundamentals", "Private Equity and Venture Capital Basics", "ESG and Sustainable Finance", "Fintech Fundamentals", "Anti-Money Laundering Fundamentals", "Forensic Accounting Fundamentals", "Payroll Fundamentals", "QuickBooks Online Skills", "Xero Accounting Skills", "Financial Mathematics", "Business Valuation for SMEs", "Insurance Fundamentals", "Cryptoassets and Digital Finance Basics", "Public Sector Accounting (IPSAS) Basics", "Accounting Ethics", "Working Capital Management", "Excel for Accountants", "Financial Regulation Overview", "Behavioural Finance", "Quantitative Finance Foundations", "Actuarial Science Foundations", "Islamic Finance Fundamentals", "Financial Reporting with IFRS 18", "Management Reporting and KPIs", "Capital Budgeting Techniques", "Wealth Management Fundamentals"]),
],
"PMB": [
    ("PM & BA Skills", F, 12, ["Project Management Fundamentals", "Agile Fundamentals", "Scrum Fundamentals", "Kanban Fundamentals", "Hybrid Project Management", "Project Scheduling and Critical Path", "Earned Value Management", "Project Risk Management", "Stakeholder Management", "Project Cost Management", "Business Analysis Fundamentals", "Requirements Elicitation", "User Stories and Backlog Management", "Process Mapping (BPMN)", "Business Process Improvement", "Change Management Fundamentals", "Product Management Fundamentals", "OKRs and Goal Setting", "Programme and Portfolio Management Basics", "Jira for Project Teams", "Lean Fundamentals", "Design Thinking", "Project Communication Management", "Agile Estimation and Planning", "Benefits Realisation Management"]),
],
"HLT": [
    ("Health Sciences Foundations", F, 20, ["Medical Terminology", "Human Anatomy and Physiology", "Pharmacology Fundamentals", "Pathophysiology", "Microbiology for Health Professions", "Nutrition Fundamentals", "Medical Ethics and Law", "Patient Safety and Quality", "Infection Prevention and Control", "Dosage Calculations for Nurses", "Health Informatics", "Public Health and Epidemiology", "Biostatistics for Health Sciences", "Mental Health Fundamentals", "First Aid Knowledge (Theory)", "Clinical Research Fundamentals (GCP)", "Healthcare Management", "Medical Billing Fundamentals", "ECG Interpretation Fundamentals", "Clinical Documentation Fundamentals", "Healthcare Compliance (HIPAA Overview)", "Evidence-Based Practice"]),
],
"ENG": [
    ("Engineering & SC Skills", I, 20, ["Supply Chain Management Fundamentals", "Logistics Fundamentals", "Procurement Fundamentals", "Inventory Management", "Demand Planning and Forecasting", "Warehouse Management", "Transportation Management", "Operations Management", "Lean Manufacturing", "Total Productive Maintenance", "Quality Management Fundamentals", "ISO 9001 Fundamentals", "Statistical Process Control", "Engineering Mathematics", "Engineering Mechanics: Statics", "Engineering Mechanics: Dynamics", "Strength of Materials", "Thermodynamics", "Fluid Mechanics", "Electrical Circuits Fundamentals", "Control Systems", "PLC Programming Fundamentals", "Engineering Drawing and GD&T", "Engineering Economics", "Health and Safety Management Fundamentals", "Construction Project Management", "Renewable Energy Fundamentals", "Industry 4.0 and IIoT", "Sustainability in Supply Chains", "Robotics Fundamentals", "Reliability Engineering Fundamentals", "Root Cause Analysis Methods", "Design for Manufacturing"]),
],
"BUS": [
    ("Business Skills", F, 10, ["Business Fundamentals", "Entrepreneurship and Startups", "Business Strategy", "Marketing Fundamentals", "Digital Marketing", "Search Engine Optimisation", "Social Media Marketing", "Content Marketing", "Email Marketing", "Sales Fundamentals", "Negotiation Skills", "Customer Success Management", "Leadership Fundamentals", "People Management", "Business Communication", "Business Writing", "Presentation Skills", "Critical Thinking and Problem Solving", "Decision Making", "Time Management and Productivity", "Emotional Intelligence at Work", "Business Law Fundamentals", "Economics Fundamentals", "International Business", "E-commerce Fundamentals", "CRM Fundamentals", "ERP Fundamentals", "Human Resources Fundamentals", "Diversity, Equity and Inclusion at Work", "Corporate Governance Fundamentals", "Business Ethics", "Customer Service Excellence", "Brand Management", "Pricing Strategy", "Operations Strategy"]),
],
"LNG": [
    ("Language Skills", F, 30, ["English Grammar Essentials", "Business English", "English Vocabulary Builder (Academic)", "English Pronunciation Foundations (Theory)", "English Reading Comprehension Strategies", "English Listening Skills Practice", "Spanish for Beginners (A1)", "French for Beginners (A1)"]),
],
"CRE": [
    ("Creative Skills", F, 12, ["Graphic Design Fundamentals", "Typography", "Colour Theory", "UI Design Fundamentals", "UX Research Fundamentals", "Figma for Designers", "Video Production for YouTube", "Video Editing Fundamentals", "Photography Fundamentals", "Motion Graphics Fundamentals", "3D Modelling with Blender", "Audio Production and Podcasting", "Copywriting", "Storytelling for Creators", "Brand Identity Design", "Illustration Fundamentals", "Animation Principles", "Thumbnail and Title Design for YouTube", "Creative Direction Basics", "Canva for Professionals"]),
],
}

# Pathways: id -> (name, category, ordered list of course "keys"). Keys are
# CATEGORY:FAMILY:SLUG for certs, or CATEGORY:title for skills.
PATHWAYS = {
    "PW-AZURE-ADMIN": ("Azure Administrator", "MIC", ["MIC:MS:AZ900", "MIC:Azure CLI and Bicep Essentials", "MIC:MS:AZ104", "MIC:MS:AZ305"]),
    "PW-AZURE-AI": ("Azure AI Engineer", "MIC", ["MIC:MS:AZ900", "MIC:MS:AI901", "MIC:MS:AI103"]),
    "PW-MS-DATA": ("Microsoft Data & Analytics", "MIC", ["MIC:MS:DP900", "MIC:MS:PL300", "MIC:MS:DP600", "MIC:MS:DP700"]),
    "PW-MS-SECURITY": ("Microsoft Security", "MIC", ["MIC:MS:SC900", "MIC:MS:SC300", "MIC:MS:SC200", "MIC:MS:SC100"]),
    "PW-POWER-PLATFORM": ("Power Platform Maker to Architect", "MIC", ["MIC:MS:PL900", "MIC:MS:PL200", "MIC:MS:PL400", "MIC:MS:PL600"]),
    "PW-AWS-ARCH": ("AWS Solutions Architect", "AWS", ["AWS:AWS:CLFC02", "AWS:AWS:SAAC03", "AWS:AWS:SAPC02"]),
    "PW-AWS-AI": ("AWS AI/ML", "AWS", ["AWS:AWS:CLFC02", "AWS:AWS:AIFC01", "AWS:AWS:MLAC01"]),
    "PW-GCP-ARCH": ("Google Cloud Architect", "GCP", ["GCP:GCP:CDL", "GCP:GCP:ACE", "GCP:GCP:PCA"]),
    "PW-GCP-DATA-AI": ("Google Cloud Data & ML", "GCP", ["GCP:GCP:CDL", "GCP:GCP:ADP", "GCP:GCP:PDE", "GCP:GCP:PMLE"]),
    "PW-SEC-CAREER": ("Cybersecurity Career", "CYB", ["CYB:CMPT:TECHPLUS", "CYB:CMPT:NETPLUS", "CYB:CMPT:SY0701", "CYB:CMPT:CYSA", "CYB:ISC2:CISSP"]),
    "PW-ISACA-AUDIT": ("IT Audit & Governance", "CYB", ["CYB:ISACA:ITAF", "CYB:ISACA:CISA", "CYB:ISACA:CRISC", "CYB:ISACA:CGEIT"]),
    "PW-CISCO-NET": ("Cisco Networking", "CYB", ["CYB:CSCO:CCSTNET", "CYB:CSCO:CCNA", "CYB:CSCO:ENCOR", "CYB:CSCO:ENARSI"]),
    "PW-ACCA": ("ACCA Qualification", "FIN", ["FIN:ACCA:BT", "FIN:ACCA:MA", "FIN:ACCA:FA", "FIN:ACCA:LW", "FIN:ACCA:PM", "FIN:ACCA:TX", "FIN:ACCA:FR", "FIN:ACCA:AA", "FIN:ACCA:FM", "FIN:ACCA:SBL", "FIN:ACCA:SBR"]),
    "PW-US-CPA": ("US CPA", "FIN", ["FIN:CPA:FAR", "FIN:CPA:AUD", "FIN:CPA:REG", "FIN:CPA:BAR"]),
    "PW-CFA": ("CFA Program", "FIN", ["FIN:CFA:L1", "FIN:CFA:L2", "FIN:CFA:L3"]),
    "PW-CIMA": ("CIMA CGMA", "FIN", ["FIN:CIMA:E1", "FIN:CIMA:P1", "FIN:CIMA:F1", "FIN:CIMA:OCS", "FIN:CIMA:E2", "FIN:CIMA:P2", "FIN:CIMA:F2", "FIN:CIMA:MCS", "FIN:CIMA:E3", "FIN:CIMA:P3", "FIN:CIMA:F3", "FIN:CIMA:SCS"]),
    "PW-PM": ("Project Management", "PMB", ["PMB:Project Management Fundamentals", "PMB:PMI:CAPM", "PMB:PMI:PMP", "PMB:PMI:PGMP"]),
    "PW-BA": ("Business Analysis", "PMB", ["PMB:Business Analysis Fundamentals", "PMB:IIBA:ECBA", "PMB:IIBA:CCBA", "PMB:IIBA:CBAP"]),
    "PW-LSS": ("Lean Six Sigma", "PMB", ["PMB:LSS:WB", "PMB:LSS:YB", "PMB:LSS:GB", "PMB:LSS:BB", "PMB:LSS:MBB"]),
    "PW-GENAI-ENG": ("Generative AI Engineer", "AI", ["AI:Machine Learning Fundamentals", "AI:Large Language Models: How They Work", "AI:Prompt Engineering Fundamentals", "AI:Retrieval-Augmented Generation (RAG)", "AI:Building AI Agents", "AI:LLMOps"]),
    "PW-AI-GOV": ("AI Governance", "AI", ["AI:Responsible AI Principles", "AI:EU AI Act Overview for Practitioners", "AI:IAPP:AIGP", "AI:ISACA:AAIA"]),
    "PW-NURSING": ("Nursing Licensure", "HLT", ["HLT:Medical Terminology", "HLT:Pharmacology Fundamentals", "HLT:NCSBN:NCLEXPN", "HLT:NCSBN:NCLEXRN"]),
    "PW-ENGLISH-TEST": ("English Proficiency Testing", "LNG", ["LNG:English Grammar Essentials", "LNG:IELTS:AC", "LNG:IELTS:GT", "LNG:ETS:TOEFL", "LNG:PEARSON:PTEA", "LNG:OET:NUR"]),
    "PW-FULLSTACK": ("Full-Stack Web Developer", "PRG", ["PRG:HTML and CSS Fundamentals", "PRG:JavaScript Fundamentals", "PRG:React Fundamentals", "PRG:Node.js Fundamentals", "PRG:REST API Design"]),
    "PW-K8S": ("Kubernetes Engineer", "PRG", ["PRG:Docker Fundamentals", "PRG:LF:KCNA", "PRG:LF:CKAD", "PRG:LF:CKA", "PRG:LF:CKS"]),
    "PW-DATA-ENG": ("Data Engineer", "DAT", ["DAT:SQL Fundamentals", "DAT:Data Engineering Fundamentals", "DAT:Apache Spark", "DAT:DBX:DEA", "DAT:SNOW:CORE"]),
    "PW-SUPPLY": ("Supply Chain Professional", "ENG", ["ENG:Supply Chain Management Fundamentals", "ENG:ASCM:CPIM", "ENG:ASCM:CSCP", "ENG:ASCM:CLTD"]),
    "PW-SALESFORCE": ("Salesforce Administrator", "BUS", ["BUS:CRM Fundamentals", "BUS:SFDC:ADM", "BUS:SFDC:PAB", "BUS:SFDC:ADVADM"]),
}

# Batch 1 course keys that receive a full curriculum spec.
BATCH1 = ["MIC:MS:AZ900", "MIC:MS:AI901", "MIC:MS:SC900", "MIC:MS:AZ104", "MIC:MS:DP900",
          "MIC:MS:PL900", "AWS:AWS:CLFC02", "CYB:CMPT:SY0701", "PMB:PMI:PMP", "FIN:CFA:L1"]

# Mandatory families that QA must find in the catalogue (family code, label).
MANDATORY_FAMILIES = [
    ("FIN", "ACCA", "ACCA papers"), ("FIN", "CPA", "US CPA sections"), ("FIN", "CMA", "CMA parts"),
    ("FIN", "CIA", "CIA parts"), ("FIN", "CFA", "CFA levels"), ("FIN", "FRM", "FRM parts"),
    ("FIN", "CAIA", "CAIA levels"), ("FIN", "CFP", "CFP"), ("FIN", "CIMA", "CIMA"), ("FIN", "EA", "EA parts"),
    ("CYB", "ISACA", "ISACA (CISA, CISM, CRISC, CGEIT, CDPSE)"),
    ("PMB", "PMI", "PMP/CAPM"), ("PMB", "PX", "PRINCE2"), ("PMB", "ITIL", "ITIL"), ("PMB", "LSS", "Lean Six Sigma belts"),
    ("PMB", "IIBA", "IIBA"), ("PMB", "SCRUM", "Scrum"),
    ("MIC", "MS", "Microsoft"), ("AWS", "AWS", "AWS"), ("GCP", "GCP", "Google Cloud"), ("CYB", "CSCO", "Cisco"),
    ("CYB", "CMPT", "CompTIA"), ("CYB", "ISC2", "ISC2"), ("PRG", "LF", "Linux Foundation"), ("PRG", "RH", "Red Hat"),
    ("PRG", "ORA", "Oracle"), ("BUS", "SAP", "SAP"), ("BUS", "SFDC", "Salesforce"), ("CYB", "SNOW", "ServiceNow"),
    ("DAT", "DBX", "Databricks"), ("DAT", "SNOW", "Snowflake"),
    ("HLT", "NCSBN", "NCLEX-RN / NCLEX-PN"),
    ("LNG", "IELTS", "IELTS Academic & General Training"), ("LNG", "ETS", "TOEFL"), ("LNG", "PEARSON", "PTE"), ("LNG", "OET", "OET"),
]

MANDATORY_CODES = ["CISA", "CISM", "CRISC", "CGEIT", "CDPSE", "PMP", "CAPM", "NCLEX-RN", "NCLEX-PN",
                   "IELTS-AC", "IELTS-GT", "ECBA", "CCBA", "CBAP", "CFA-L1", "CFA-L2", "CFA-L3",
                   "AUD", "FAR", "REG", "BAR", "ISC", "TCP"]
