"""Batch 1 curriculum specifications.

Domain names/weightings for the six Microsoft exams were copied from the
official study guides fetched via the Microsoft Learn MCP on 2026-10-02.
The other four (CLF-C02, SY0-701, PMP, CFA Level I) rest on search-snippet
evidence only, because the official sites were blocked by the egress proxy;
they are labelled accordingly and MUST be re-checked before production.

Mock lengths: where the official length was not read on an official page this
session, the mock spec is marked as a design assumption.
"""

OFFICIAL = "verified-official-source"
SECONDARY = "secondary-only-needs-official-check"

CURRICULA = {
"MIC:MS:AZ900": dict(
    code="AZ-900", source="SRC-MS-AZ900", evidence=OFFICIAL, effective="Skills measured as of 2026-07-20",
    outcomes=["Explain cloud computing models, service types and the shared responsibility model",
              "Identify core Azure architectural components and services for compute, networking and storage",
              "Describe Azure identity, access and security capabilities",
              "Describe Azure cost management, governance, deployment and monitoring tools"],
    domains=[
        ("Describe cloud concepts", "25-30%", ["Describe cloud computing", "Describe the benefits of using cloud services", "Describe cloud service types"]),
        ("Describe Azure architecture and services", "35-40%", ["Describe the core architectural components of Azure", "Describe Azure compute and networking services", "Describe Azure storage services", "Describe Azure identity, access, and security"]),
        ("Describe Azure management and governance", "30-35%", ["Describe cost management in Azure", "Describe features and tools in Azure for governance and compliance", "Describe features and tools for managing and deploying Azure resources", "Describe monitoring tools in Azure"]),
    ],
    mock=dict(items=45, minutes=45, basis="DESIGN ASSUMPTION - the study guide fetched does not state question count or duration; confirm on the exam details page."),
    samples=[
        ("A company wants to pay only for compute it actually uses and avoid buying servers up front. Which cloud benefit does this describe?",
         [("Consumption-based (pay-as-you-go) pricing", True, "Correct: the consumption-based model charges for resources used and moves spend from CapEx to OpEx."),
          ("High availability", False, "Availability is about uptime, not how resources are paid for."),
          ("Data sovereignty", False, "Sovereignty concerns where data is stored and which laws apply, not billing."),
          ("Vertical scaling", False, "Vertical scaling changes resource size; it says nothing about payment model.")]),
        ("Which Azure construct lets you apply Azure Policy and RBAC across several subscriptions at once?",
         [("Resource group", False, "A resource group lives inside one subscription, so it cannot span several."),
          ("Management group", True, "Correct: management groups sit above subscriptions and pass on policy and access to every subscription under them."),
          ("Availability zone", False, "Availability zones are physical datacenter groupings for resiliency, not a governance scope."),
          ("Resource lock", False, "Locks stop resources being deleted or changed. They do not group subscriptions.")]),
        ("In the shared responsibility model, which responsibility always stays with the customer, whatever the service type (IaaS, PaaS or SaaS)?",
         [("Physical datacenter security", False, "Physical security is always the cloud provider's responsibility."),
          ("Operating system patching", False, "OS patching is the customer's job in IaaS but the provider's in PaaS and SaaS."),
          ("Information and data, including accounts and identities", True, "Correct: customers always own their data, devices, accounts and identities."),
          ("Network controls for the host", False, "Host network controls move to the provider in PaaS and SaaS.")]),
    ]),
"MIC:MS:AI901": dict(
    code="AI-901", source="SRC-MS-AI901", evidence=OFFICIAL, effective="Skills measured as of 2026-04-15 (AI-900 retired 2026-06-30)",
    outcomes=["Apply responsible AI principles to solution scenarios",
              "Select appropriate AI models, deployment options and configuration parameters",
              "Identify generative, agentic, text, speech, vision and information-extraction workloads",
              "Describe how to build lightweight apps and agents with Microsoft Foundry and Foundry Tools"],
    domains=[
        ("Identify AI concepts and capabilities", "40-45%", ["Describe principles of responsible AI", "Identify AI model components and configurations", "Identify AI workloads"]),
        ("Implement AI solutions by using Microsoft Foundry", "55-60%", ["Implement generative AI apps and agents by using Foundry", "Implement AI solutions for text and speech by using Foundry", "Implement AI solutions with computer vision and image-generation capabilities by using Foundry", "Implement AI solutions for information extraction by using Foundry"]),
    ],
    mock=dict(items=45, minutes=45, basis="DESIGN ASSUMPTION - length not stated on the fetched study guide."),
    samples=[
        ("An AI loan-approval system gives very different approval rates to applicants with otherwise similar profiles but different genders. Which responsible AI principle is most directly affected?",
         [("Fairness", True, "Correct: fairness means AI systems treat similar people in similar ways."),
          ("Transparency", False, "Transparency is about explaining how the system works. The problem here is unequal outcomes."),
          ("Reliability and safety", False, "Reliability is about performing consistently under expected conditions, not about bias between groups."),
          ("Inclusiveness", False, "Inclusiveness is about designing for people of every ability. Fairness is the closer match.")]),
        ("You need to pull fields from scanned invoices, and also from recorded call audio, using one Foundry Tools capability. Which should you choose?",
         [("Azure Speech in Foundry Tools", False, "Speech covers recognition and synthesis. It does not extract structured fields from documents."),
          ("Azure Content Understanding in Foundry Tools", True, "Correct: the skills outline lists Content Understanding for extraction from documents, images, audio and video."),
          ("An image-generation model", False, "Image-generation models create images. They do not extract fields."),
          ("A text analysis sentiment feature", False, "Sentiment analysis scores opinion. It does not extract invoice fields or handle audio.")]),
        ("Which change is MOST likely to make a deployed generative model's answers more deterministic?",
         [("Increasing temperature", False, "A higher temperature increases randomness."),
          ("Lowering temperature", True, "Correct: a lower temperature concentrates sampling on the most likely tokens, so output is more consistent."),
          ("Adding more sample images to the prompt", False, "Image inputs do not control sampling randomness."),
          ("Switching to a speech model", False, "Changing the modality does not address determinism.")]),
    ]),
"MIC:MS:SC900": dict(
    code="SC-900", source="SRC-MS-SC900", evidence=OFFICIAL, effective="Skills measured as of 2026-10-21 (published update)",
    outcomes=["Describe security, compliance and identity concepts including Zero Trust",
              "Describe Microsoft Entra identity, authentication, access and governance capabilities",
              "Describe Microsoft security solutions across Azure, Sentinel and Defender XDR",
              "Describe Microsoft Purview compliance, information protection and eDiscovery capabilities"],
    domains=[
        ("Describe the concepts of security, compliance, and identity", "10-15%", ["Describe security and compliance concepts", "Define identity concepts"]),
        ("Describe the capabilities of Microsoft Entra", "25-30%", ["Describe function and identity types of Microsoft Entra ID", "Describe authentication capabilities of Microsoft Entra ID", "Describe access management capabilities of Microsoft Entra ID", "Describe identity protection and governance capabilities of Microsoft Entra"]),
        ("Describe the capabilities of Microsoft security solutions", "35-40%", ["Describe core infrastructure security services in Azure", "Describe security management capabilities of Azure", "Describe capabilities of Microsoft Sentinel", "Describe threat protection with Microsoft Defender XDR"]),
        ("Describe the capabilities of Microsoft compliance solutions", "20-25%", ["Describe Microsoft Service Trust Portal and privacy principles", "Describe compliance management capabilities of Microsoft Purview", "Describe information protection, data lifecycle management, and data governance capabilities of Microsoft Purview", "Describe insider risk, eDiscovery, and audit capabilities in Microsoft Purview"]),
    ],
    mock=dict(items=45, minutes=45, basis="DESIGN ASSUMPTION - length not stated on the fetched study guide."),
    samples=[
        ("Which Zero Trust principle is applied when every access request is authenticated and authorised using all available signals?",
         [("Verify explicitly", True, "Correct: 'verify explicitly' means authenticating and authorising on every available data point."),
          ("Use least privilege access", False, "Least privilege limits how much access is granted. It does not cover how each request is checked."),
          ("Assume breach", False, "Assume breach is about limiting blast radius and segmenting access."),
          ("Defense-in-depth", False, "Defense-in-depth is a layered security model, not one of the three Zero Trust principles.")]),
        ("Which service gives you a cloud-native SIEM with SOAR capabilities?",
         [("Microsoft Defender for Cloud", False, "Defender for Cloud does CSPM and workload protection. It is not the SIEM."),
          ("Microsoft Sentinel", True, "Correct: the skills outline places SIEM/SOAR concepts under Microsoft Sentinel."),
          ("Azure Firewall", False, "Azure Firewall is a network security service."),
          ("Microsoft Purview Compliance Manager", False, "Compliance Manager tracks regulatory compliance posture.")]),
        ("A user must give a second form of verification only when signing in from an unfamiliar country. Which Entra capability enforces this?",
         [("Self-service password reset", False, "SSPR lets users reset passwords. It does not set sign-in conditions."),
          ("Conditional Access", True, "Correct: Conditional Access policies use signals such as location to require MFA."),
          ("Privileged Identity Management", False, "PIM gives just-in-time privileged roles. It does not enforce location-based MFA."),
          ("Access reviews", False, "Access reviews recertify existing access from time to time.")]),
    ]),
"MIC:MS:AZ104": dict(
    code="AZ-104", source="SRC-MS-AZ104", evidence=OFFICIAL, effective="Skills measured as of 2026-04-17",
    outcomes=["Manage Entra users/groups, RBAC and subscription governance",
              "Configure and secure storage accounts, Azure Files and Blob Storage",
              "Deploy compute using ARM/Bicep, VMs, containers and App Service",
              "Implement and secure virtual networking, DNS and load balancing",
              "Monitor resources and implement backup and site recovery"],
    domains=[
        ("Manage Azure identities and governance", "20-25%", ["Manage Microsoft Entra users and groups", "Manage access to Azure resources", "Manage Azure subscriptions and governance"]),
        ("Implement and manage storage", "15-20%", ["Configure access to storage", "Configure and manage storage accounts", "Configure Azure Files and Azure Blob Storage"]),
        ("Deploy and manage Azure compute resources", "20-25%", ["Automate deployment of resources by using ARM templates or Bicep files", "Create and configure virtual machines", "Provision and manage containers in the Azure portal", "Create and configure Azure App Service"]),
        ("Implement and manage virtual networking", "15-20%", ["Configure and manage virtual networks in Azure", "Configure secure access to virtual networks", "Configure name resolution and load balancing"]),
        ("Monitor and maintain Azure resources", "10-15%", ["Monitor resources in Azure", "Implement backup and recovery"]),
    ],
    mock=dict(items=50, minutes=100, basis="DESIGN ASSUMPTION - length not stated on the fetched study guide; the real exam includes non-MCQ item types, which Mastemy turns into MCQ/MR only."),
    samples=[
        ("You must give a user permission to manage VMs in one resource group only, not anywhere else in the subscription. What should you do?",
         [("Assign Virtual Machine Contributor at the resource group scope", True, "Correct: an RBAC role assigned at resource-group scope applies only to resources in that group."),
          ("Assign Virtual Machine Contributor at the subscription scope", False, "Subscription scope would cover every resource group, which gives too much access."),
          ("Assign Owner at the resource group scope", False, "Owner also lets the user manage access. That breaks least privilege."),
          ("Create an Azure Policy assignment", False, "Policy controls resource configuration. It does not grant user permissions.")]),
        ("Blobs not accessed for 90 days must move to the cool tier automatically. What do you configure?",
         [("Object replication", False, "Object replication copies blobs between accounts. It does not change their tier."),
          ("Blob lifecycle management policy", True, "Correct: lifecycle management rules move blobs between tiers based on age or last access."),
          ("Soft delete for blobs", False, "Soft delete keeps deleted data. It does not move data between tiers."),
          ("Stored access policy", False, "Stored access policies control SAS permissions.")]),
        ("Which feature lets VMs in two virtual networks talk to each other over the Microsoft backbone without a gateway?",
         [("Virtual network peering", True, "Correct: peering connects VNets with low-latency private connectivity and no VPN gateway."),
          ("Service endpoint", False, "Service endpoints secure access from a VNet to PaaS services."),
          ("User-defined route", False, "UDRs override routing but do not join separate VNets on their own."),
          ("Azure Bastion", False, "Bastion gives browser-based RDP/SSH access to VMs.")]),
    ]),
"MIC:MS:DP900": dict(
    code="DP-900", source="SRC-MS-DP900", evidence=OFFICIAL, effective="Skills measured as of 2026-07-21",
    outcomes=["Describe structured, semi-structured and unstructured data and common data workloads",
              "Explain relational concepts and the Azure SQL family",
              "Describe Azure non-relational storage and Azure Cosmos DB",
              "Describe large-scale and real-time analytics and Power BI visualisation"],
    domains=[
        ("Describe core data concepts", "25-30%", ["Describe ways to represent data", "Identify options for data storage", "Describe common data workloads", "Identify roles and responsibilities for data workloads"]),
        ("Identify considerations for relational data on Azure", "20-25%", ["Describe relational concepts", "Describe relational Azure data services"]),
        ("Describe considerations for working with non-relational data on Azure", "15-20%", ["Describe the capabilities of Azure storage", "Describe the capabilities and features of Azure Cosmos DB"]),
        ("Describe an analytics workload", "25-30%", ["Describe common elements of large-scale analytics", "Describe considerations for real-time data analytics", "Describe data visualization in Microsoft Power BI"]),
    ],
    mock=dict(items=45, minutes=45, basis="DESIGN ASSUMPTION - length not stated on the fetched study guide."),
    samples=[
        ("A JSON document with nested, optional fields is an example of which kind of data?",
         [("Structured", False, "Structured data follows a fixed tabular schema."),
          ("Semi-structured", True, "Correct: JSON carries its own flexible structure through keys and nesting."),
          ("Unstructured", False, "Unstructured data, such as images or free text, has no organising tags."),
          ("Normalised", False, "Normalisation is a relational design process, not a type of data.")]),
        ("Why do we normalise a relational database?",
         [("To reduce data duplication and update anomalies", True, "Correct: normalisation splits data into related tables so each fact is stored once."),
          ("To make all queries faster", False, "Normalisation can slow reads by adding joins."),
          ("To store images efficiently", False, "Normalisation has nothing to do with binary storage."),
          ("To allow schema-less writes", False, "Schema-less writes are a feature of NoSQL stores.")]),
        ("Which service is a globally distributed, multi-model NoSQL database with several APIs?",
         [("Azure SQL Managed Instance", False, "This is a relational SQL Server-compatible service."),
          ("Azure Table storage", False, "Table storage is a simple key/attribute store without the multiple APIs."),
          ("Azure Cosmos DB", True, "Correct: Cosmos DB offers several APIs and global distribution."),
          ("Azure Files", False, "Azure Files provides SMB/NFS file shares.")]),
    ]),
"MIC:MS:PL900": dict(
    code="PL-900", source="SRC-MS-PL900", evidence=OFFICIAL, effective="Skills measured as of 2026-07-24",
    outcomes=["Describe the business value of Power Platform services including Copilot Studio",
              "Describe Dataverse and Power Platform administration and governance",
              "Describe how canvas, model-driven and AI-assisted apps are built",
              "Describe cloud and desktop flows and how to build them with AI",
              "Describe building and managing agents in Copilot Studio"],
    domains=[
        ("Describe the business value of Microsoft Power Platform", "5-10%", ["Describe the business value of Microsoft Power Platform services"]),
        ("Manage the Microsoft Power Platform environment", "20-25%", ["Describe Microsoft Dataverse", "Describe Microsoft Power Platform administration and governance"]),
        ("Demonstrate the capabilities of Power Apps", "20-25%", ["Describe Power Apps capabilities and use cases", "Describe how to build basic apps by using Power Apps"]),
        ("Demonstrate the capabilities of Power Automate", "20-25%", ["Describe Power Automate use cases and capabilities", "Describe how to build basic flows by using Power Automate"]),
        ("Describe features and capabilities of agents in Microsoft Copilot Studio", "20-25%", ["Describe how to build agents in Copilot Studio", "Describe how to manage agents in Copilot Studio"]),
    ],
    mock=dict(items=45, minutes=45, basis="DESIGN ASSUMPTION - length not stated on the fetched study guide."),
    samples=[
        ("A team needs an app built on top of a Dataverse data model, with forms and views generated from that model. Which app type fits best?",
         [("Canvas app", False, "Canvas apps start from a blank screen layout, not from the data model."),
          ("Model-driven app", True, "Correct: model-driven apps generate their UI from Dataverse tables, forms and views."),
          ("Desktop flow", False, "Desktop flows automate legacy UI tasks. They are not apps."),
          ("Power Pages site", False, "Power Pages builds external websites.")]),
        ("Which Power Automate flow type automates clicks in a legacy Windows application with no API?",
         [("Cloud flow with a connector trigger", False, "Cloud flows need connectors or APIs."),
          ("Desktop flow", True, "Correct: desktop flows (RPA) automate UI interactions on Windows."),
          ("Business process flow", False, "Business process flows guide users through stages. They do not automate UI."),
          ("Scheduled cloud flow", False, "A schedule is still a cloud flow and cannot drive a desktop UI.")]),
        ("In Copilot Studio, what do you use to define a structured conversation path that triggers on certain user phrases?",
         [("Topics", True, "Correct: topics define conversation paths that start from trigger phrases."),
          ("Channels", False, "Channels are where the agent is published."),
          ("Environments", False, "Environments are containers for administration."),
          ("Knowledge sources", False, "Knowledge sources supply grounding content. They do not script a dialogue path.")]),
    ]),
"AWS:AWS:CLFC02": dict(
    code="CLF-C02", source="SRC-AWS-CLF", evidence=SECONDARY, effective="Exam guide (version not confirmed - official PDF blocked)",
    outcomes=["Describe the AWS Cloud value proposition and cloud economics",
              "Explain the shared responsibility model, IAM and AWS security/compliance services",
              "Identify core AWS compute, storage, database, networking and AI services",
              "Compare AWS pricing models, cost tools and support plans"],
    domains=[
        ("Cloud Concepts", "24%", ["Benefits of the AWS Cloud", "Design principles of the AWS Cloud", "Migration to the AWS Cloud", "Cloud economics"]),
        ("Security and Compliance", "30%", ["Shared responsibility model", "Security, governance and compliance concepts", "AWS access management", "Security components and resources"]),
        ("Cloud Technology and Services", "34%", ["Deploying and operating in the AWS Cloud", "AWS global infrastructure", "Compute services", "Database services", "Network services", "Storage services", "AI/ML and analytics services", "Other in-scope services"]),
        ("Billing, Pricing, and Support", "12%", ["Pricing models", "Billing, budget and cost management", "Technical resources and support options"]),
    ],
    mock=dict(items=65, minutes=90, basis="From search snippets (65 questions / 90 min) - official exam guide not retrieved; re-verify."),
    samples=[
        ("Under the shared responsibility model, which task belongs to AWS for Amazon EC2?",
         [("Patching the guest operating system", False, "On EC2 (IaaS) the customer patches the guest OS."),
          ("Configuring security groups", False, "Security group rules are set by the customer."),
          ("Securing the physical hosts and the virtualisation layer", True, "Correct: AWS is responsible for security OF the cloud: hardware, facilities and the hypervisor."),
          ("Encrypting application data", False, "The customer chooses and manages data encryption.")]),
        ("Which pricing model gives the biggest discount for steady, predictable usage in return for a 1- or 3-year commitment?",
         [("On-Demand", False, "On-Demand has no commitment and no discount."),
          ("Savings Plans / Reserved Instances", True, "Correct: commitment-based models trade a term commitment for lower rates."),
          ("Spot Instances", False, "Spot gives deep discounts but can be interrupted, so it does not suit steady predictable load."),
          ("Dedicated Hosts on-demand", False, "Dedicated Hosts cost more and are used for licensing or compliance reasons.")]),
        ("Which AWS service records API calls made in an account, for auditing?",
         [("Amazon CloudWatch", False, "CloudWatch handles metrics, logs and alarms. API audit trails come from CloudTrail."),
          ("AWS CloudTrail", True, "Correct: CloudTrail records API activity for governance and audit."),
          ("AWS Config", False, "Config records resource configuration state, not API calls."),
          ("Amazon Inspector", False, "Inspector scans for vulnerabilities.")]),
    ]),
"CYB:CMPT:SY0701": dict(
    code="SY0-701", source="SRC-COMPTIA-SECPLUS", evidence=SECONDARY, effective="SY0-701 objectives (reported English retirement 2027-06-11; SY0-801 in draft)",
    outcomes=["Explain fundamental security concepts and controls",
              "Analyse threats, vulnerabilities and mitigations",
              "Evaluate security architecture across on-premises, cloud and hybrid",
              "Apply security operations practices including IR and monitoring",
              "Describe security programme management, risk and compliance"],
    domains=[
        ("General Security Concepts", "12%", ["Security controls", "Fundamental security concepts", "Change management", "Cryptographic solutions"]),
        ("Threats, Vulnerabilities, and Mitigations", "22%", ["Threat actors and motivations", "Threat vectors and attack surfaces", "Vulnerability types", "Indicators of malicious activity", "Mitigation techniques"]),
        ("Security Architecture", "18%", ["Architecture models", "Securing enterprise infrastructure", "Data protection", "Resilience and recovery"]),
        ("Security Operations", "28%", ["Applying security techniques to computing resources", "Asset management", "Vulnerability management", "Alerting and monitoring", "Enterprise capability changes", "Identity and access management", "Automation and orchestration", "Incident response", "Using data sources for investigations"]),
        ("Security Program Management and Oversight", "20%", ["Security governance", "Risk management", "Third-party risk", "Compliance", "Audits and assessments", "Security awareness"]),
    ],
    mock=dict(items=90, minutes=90, basis="DESIGN ASSUMPTION based on widely reported 'max 90 questions / 90 min' - NOT verified this session. Performance-based items are not reproducible in MCQ-only format."),
    samples=[
        ("Which control type is a security guard checking badges at a building entrance?",
         [("Technical", False, "Technical controls are implemented in technology, such as firewalls."),
          ("Physical", True, "Correct: guards, locks and fences are physical controls."),
          ("Managerial", False, "Managerial controls are policies and risk assessments."),
          ("Compensating", False, "Compensating describes the control's function, not its category. A guard could be compensating, but 'physical' is the best category here.")]),
        ("An attacker sends texts pretending to be the bank and asking users to confirm credentials. What is this?",
         [("Vishing", False, "Vishing uses voice calls."),
          ("Smishing", True, "Correct: smishing is phishing over SMS."),
          ("Whaling", False, "Whaling targets senior executives, usually by email."),
          ("Pharming", False, "Pharming redirects traffic by poisoning DNS or hosts files.")]),
        ("In incident response, which phase directly follows detection/analysis in the commonly used lifecycle?",
         [("Preparation", False, "Preparation comes before detection."),
          ("Containment", True, "Correct: once an incident is confirmed, you contain it before eradication and recovery."),
          ("Lessons learned", False, "Lessons learned comes at the end."),
          ("Recovery", False, "Recovery follows containment and eradication.")]),
    ]),
"PMB:PMI:PMP": dict(
    code="PMP", source="SRC-PMI-PMP-2026", evidence=SECONDARY, effective="PMP ECO effective 2026-07-09 (reported); task list not retrieved",
    outcomes=["Lead and develop high-performing project teams across predictive, agile and hybrid approaches",
              "Plan, execute and control scope, schedule, cost, quality, risk and procurement",
              "Connect projects to organisational strategy, value delivery and compliance",
              "Choose a delivery approach that fits the context"],
    domains=[
        ("People", "33%", ["Team leadership and servant leadership", "Building and developing teams", "Conflict and stakeholder engagement", "Coaching, mentoring and emotional intelligence"]),
        ("Process", "41%", ["Delivery approach selection (predictive/agile/hybrid)", "Scope and requirements", "Schedule and cost management", "Quality management", "Risk management", "Procurement and contracts", "Integration and change control", "Project closure and knowledge transfer"]),
        ("Business Environment", "26%", ["Strategy alignment and benefits realisation", "Value delivery and measurement", "Compliance and governance", "Organisational change and external environment"]),
    ],
    mock=dict(items=180, minutes=230, basis="DESIGN ASSUMPTION from the pre-2026 format (180 q / 230 min) - the 2026 ECO length was NOT verified this session; adjust when confirmed. Lesson titles are Mastemy groupings, not official ECO task names (task list not retrieved)."),
    samples=[
        ("Two senior team members keep clashing over technical design and it is delaying the work. What should the project manager do FIRST?",
         [("Escalate to the sponsor", False, "Escalating straight away skips the PM's own job of resolving team conflict."),
          ("Meet both members to understand the root cause and work together on a solution", True, "Correct: collaborating / problem-solving deals with the cause and is the preferred first approach."),
          ("Assign the design decision to the more senior member", False, "Forcing a result may resolve things in the short term but damages team cohesion."),
          ("Remove one member from the project", False, "This is a last resort and premature here.")]),
        ("In an adaptive project, who is mainly responsible for maximising product value by ordering the backlog?",
         [("Project sponsor", False, "The sponsor funds the work and champions it, but does not order the backlog."),
          ("Product owner", True, "Correct: the product owner orders the backlog to maximise value."),
          ("Scrum master / team facilitator", False, "The facilitator serves the team and removes impediments."),
          ("Developers", False, "Developers estimate and deliver items. They do not own backlog order.")]),
        ("A new regulation affects the project's deliverables halfway through. Which domain does handling this mainly fall under?",
         [("People", False, "This is not mainly a team or leadership issue."),
          ("Process", False, "Process covers the change control that follows, but recognising external compliance impacts belongs to Business Environment."),
          ("Business Environment", True, "Correct: compliance and changes in the external environment sit in Business Environment."),
          ("None - regulations are out of PMP scope", False, "Compliance is explicitly within PMP scope.")]),
    ]),
"FIN:CFA:L1": dict(
    code="CFA Level I", source="SRC-CFA-L1", evidence=SECONDARY, effective="Topic weights reported for 2026 (third-party summary); LOS not retrieved",
    outcomes=["Apply the CFA Institute Code and Standards to ethical dilemmas",
              "Use quantitative, economic and financial-statement tools to analyse issuers",
              "Value equity, fixed-income and derivative instruments at a foundational level",
              "Describe alternative investments and portfolio-management principles"],
    domains=[
        ("Ethical and Professional Standards", "15-20%", ["Ethics and trust", "Code of Ethics and Standards of Professional Conduct", "Guidance for Standards I-VII", "GIPS introduction"]),
        ("Quantitative Methods", "6-9%", ["Rates and returns", "Time value of money", "Statistical measures and probability", "Sampling, estimation and hypothesis testing", "Simple linear regression"]),
        ("Economics", "6-9%", ["Firm and market structures", "Business cycles and policy", "International trade and currency exchange"]),
        ("Financial Statement Analysis", "11-14%", ["Financial reporting framework", "Income statement, balance sheet and cash flows", "Inventories, long-lived assets, taxes and liabilities", "Financial analysis techniques and quality"]),
        ("Corporate Issuers", "6-9%", ["Corporate structures and governance", "Capital investments and cost of capital", "Capital structure and working capital"]),
        ("Equity Investments", "11-14%", ["Market organisation and indexes", "Market efficiency", "Industry and company analysis", "Equity valuation concepts"]),
        ("Fixed Income", "11-14%", ["Instrument features and cash flows", "Pricing, yields and spreads", "Interest-rate risk and duration", "Credit risk and securitisation"]),
        ("Derivatives", "5-8%", ["Derivative markets and instruments", "Forward commitment and contingent claim pricing", "Arbitrage, replication and put-call parity"]),
        ("Alternative Investments", "7-10%", ["Features and structures", "Private capital, real estate and infrastructure", "Hedge funds, commodities and digital assets"]),
        ("Portfolio Management", "8-12%", ["Portfolio risk and return", "Portfolio planning and construction", "Behavioural biases and risk management"]),
    ],
    mock=dict(items=180, minutes=270, basis="DESIGN ASSUMPTION (widely reported 180 items over two sessions) - NOT verified this session. Lesson groupings are Mastemy's and are not the official LOS; LOS-level traceability is pending retrieval of the official curriculum."),
    samples=[
        ("A research analyst gets a valuable gift from a company she covers, and it could reasonably compromise her independence. Under the Standards she should:",
         [("Accept it and disclose it only if asked", False, "Gifts that could compromise independence must be refused, or disclosed and approved as the Standards require."),
          ("Decline the gift", True, "Correct: under Independence and Objectivity, members must not accept gifts that could reasonably compromise independence."),
          ("Accept it as long as the research rating stays the same", False, "The test is whether the gift could reasonably compromise independence, not what actually happens to the rating."),
          ("Pass it on to her employer", False, "Giving it to the employer does not remove the conflict.")]),
        ("All else equal, which bond has the highest Macaulay duration?",
         [("A 5-year 8% coupon bond", False, "A shorter maturity and a higher coupon both lower duration."),
          ("A 10-year 8% coupon bond", False, "A higher coupon lowers duration compared with a zero."),
          ("A 10-year zero-coupon bond", True, "Correct: a zero's duration equals its maturity, the highest of these options."),
          ("A 10-year 4% coupon bond", False, "Coupons pull duration below maturity.")]),
        ("A 1-year call and put on the same non-dividend stock share a strike of 100. The stock is 100 and the risk-free rate is 5%. Put-call parity implies c - p is about:",
         [("0", False, "That ignores the present value of the strike."),
          ("4.76", True, "Correct: c - p = S - K/(1+r)^T = 100 - 100/1.05 = 4.76."),
          ("5.00", False, "This uses K x r instead of discounting the strike."),
          ("-4.76", False, "The sign is reversed. With S equal to K, calls are worth more than puts.")]),
    ]),
}
