using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Mastemy.Api.Modules.Identity;

/// <summary>1:1 security side table for <see cref="Domain.User"/>: email verification and TOTP MFA state.</summary>
public class UserSecurity
{
    public Guid UserId { get; set; }
    public DateTime? EmailVerifiedAt { get; set; }
    /// <summary>Email address that was verified; a changed address is no longer verified.</summary>
    public string? VerifiedEmail { get; set; }
    /// <summary>Active TOTP secret, encrypted with <see cref="Infrastructure.SecretProtector"/>.</summary>
    public string? MfaSecretProtected { get; set; }
    public DateTime? MfaEnabledAt { get; set; }
    /// <summary>Secret generated by an enrollment that has not been confirmed yet (encrypted).</summary>
    public string? MfaPendingSecretProtected { get; set; }
    public DateTime? MfaPendingCreatedAt { get; set; }
    /// <summary>Highest TOTP time step accepted so far; codes for this or earlier steps are rejected (replay protection).</summary>
    public long? MfaLastUsedStep { get; set; }
    public DateTime? PasswordChangedAt { get; set; }
}

public enum OneTimeTokenPurpose { EmailVerification = 1, PasswordReset = 2 }

/// <summary>Single-use, hashed, expiring token (email verification / password reset).</summary>
public class OneTimeToken
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid UserId { get; set; }
    public OneTimeTokenPurpose Purpose { get; set; }
    public string TokenHash { get; set; } = "";
    /// <summary>Email address the token was sent to.</summary>
    public string Email { get; set; } = "";
    public DateTime ExpiresAt { get; set; }
    public DateTime? UsedAt { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
}

public class MfaRecoveryCode
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid UserId { get; set; }
    public string CodeHash { get; set; } = "";
    public DateTime? UsedAt { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
}

/// <summary>Second-factor challenge created by a password login of an MFA-enrolled user.</summary>
public class MfaChallenge
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid UserId { get; set; }
    public string TokenHash { get; set; } = "";
    public DateTime ExpiresAt { get; set; }
    public DateTime? UsedAt { get; set; }
    public int FailedAttempts { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
}

/// <summary>Session metadata for a refresh-token family (one login).</summary>
public class AuthSession
{
    public Guid FamilyId { get; set; }
    public Guid UserId { get; set; }
    public bool MfaAuthenticated { get; set; }
    public string UserAgent { get; set; } = "";
    public string IpAddress { get; set; } = "";
    public string LastIpAddress { get; set; } = "";
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime LastUsedAt { get; set; } = DateTime.UtcNow;
}

public class UserSecurityConfig : IEntityTypeConfiguration<UserSecurity>
{
    public void Configure(EntityTypeBuilder<UserSecurity> b)
    {
        b.ToTable("Identity_UserSecurity");
        b.HasKey(x => x.UserId);
        b.Property(x => x.VerifiedEmail).HasMaxLength(254);
        b.Property(x => x.MfaSecretProtected).HasColumnType("longtext");
        b.Property(x => x.MfaPendingSecretProtected).HasColumnType("longtext");
        b.HasOne<Domain.User>().WithOne().HasForeignKey<UserSecurity>(x => x.UserId).OnDelete(DeleteBehavior.Cascade);
    }
}

public class OneTimeTokenConfig : IEntityTypeConfiguration<OneTimeToken>
{
    public void Configure(EntityTypeBuilder<OneTimeToken> b)
    {
        b.ToTable("Identity_OneTimeTokens");
        b.HasKey(x => x.Id);
        b.Property(x => x.TokenHash).HasMaxLength(64).IsRequired();
        b.Property(x => x.Email).HasMaxLength(254).IsRequired();
        b.HasIndex(x => x.TokenHash).IsUnique();
        b.HasIndex(x => new { x.UserId, x.Purpose, x.CreatedAt });
        b.HasOne<Domain.User>().WithMany().HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Cascade);
    }
}

public class MfaRecoveryCodeConfig : IEntityTypeConfiguration<MfaRecoveryCode>
{
    public void Configure(EntityTypeBuilder<MfaRecoveryCode> b)
    {
        b.ToTable("Identity_MfaRecoveryCodes");
        b.HasKey(x => x.Id);
        b.Property(x => x.CodeHash).HasMaxLength(64).IsRequired();
        b.HasIndex(x => new { x.UserId, x.CodeHash });
        b.HasOne<Domain.User>().WithMany().HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Cascade);
    }
}

public class MfaChallengeConfig : IEntityTypeConfiguration<MfaChallenge>
{
    public void Configure(EntityTypeBuilder<MfaChallenge> b)
    {
        b.ToTable("Identity_MfaChallenges");
        b.HasKey(x => x.Id);
        b.Property(x => x.TokenHash).HasMaxLength(64).IsRequired();
        b.HasIndex(x => x.TokenHash).IsUnique();
        b.HasIndex(x => x.UserId);
        b.HasOne<Domain.User>().WithMany().HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Cascade);
    }
}

public class AuthSessionConfig : IEntityTypeConfiguration<AuthSession>
{
    public void Configure(EntityTypeBuilder<AuthSession> b)
    {
        b.ToTable("Identity_AuthSessions");
        b.HasKey(x => x.FamilyId);
        b.Property(x => x.UserAgent).HasMaxLength(512).IsRequired();
        b.Property(x => x.IpAddress).HasMaxLength(64).IsRequired();
        b.Property(x => x.LastIpAddress).HasMaxLength(64).IsRequired();
        b.HasIndex(x => x.UserId);
        b.HasOne<Domain.User>().WithMany().HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Cascade);
    }
}
